//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pdw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pdw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigToSmallFont {
            get {
                object obj = ResourceManager.GetObject("BigToSmallFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bookmarks {
            get {
                object obj = ResourceManager.GetObject("Bookmarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart {
            get {
                object obj = ResourceManager.GetObject("chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CollapseHover {
            get {
                object obj = ResourceManager.GetObject("CollapseHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CollapsiblePanelBg {
            get {
                object obj = ResourceManager.GetObject("CollapsiblePanelBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorblack {
            get {
                object obj = ResourceManager.GetObject("colorblack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorblue {
            get {
                object obj = ResourceManager.GetObject("colorblue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorbrightgreen {
            get {
                object obj = ResourceManager.GetObject("colorbrightgreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colordarkblue {
            get {
                object obj = ResourceManager.GetObject("colordarkblue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colordarkred {
            get {
                object obj = ResourceManager.GetObject("colordarkred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colordarkyellow {
            get {
                object obj = ResourceManager.GetObject("colordarkyellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorgray25 {
            get {
                object obj = ResourceManager.GetObject("colorgray25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorgray50 {
            get {
                object obj = ResourceManager.GetObject("colorgray50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorgreen {
            get {
                object obj = ResourceManager.GetObject("colorgreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colornocolor {
            get {
                object obj = ResourceManager.GetObject("colornocolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorpink {
            get {
                object obj = ResourceManager.GetObject("colorpink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorred {
            get {
                object obj = ResourceManager.GetObject("colorred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorteal {
            get {
                object obj = ResourceManager.GetObject("colorteal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorturquoise {
            get {
                object obj = ResourceManager.GetObject("colorturquoise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap colorviolet {
            get {
                object obj = ResourceManager.GetObject("colorviolet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coloryellow {
            get {
                object obj = ResourceManager.GetObject("coloryellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Comment {
            get {
                object obj = ResourceManager.GetObject("Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Document_Preview_icon {
            get {
                object obj = ResourceManager.GetObject("Document_Preview_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DomainAddSection {
            get {
                object obj = ResourceManager.GetObject("DomainAddSection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a domain.
        /// </summary>
        internal static string DomainComboBoxText {
            get {
                return ResourceManager.GetString("DomainComboBoxText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DomainNormal {
            get {
                object obj = ResourceManager.GetObject("DomainNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpandHover {
            get {
                object obj = ResourceManager.GetObject("ExpandHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Foreach {
            get {
                object obj = ResourceManager.GetObject("Foreach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_fix {
            get {
                object obj = ResourceManager.GetObject("Icon_fix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageHolder {
            get {
                object obj = ResourceManager.GetObject("ImageHolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_AddBookmarkError {
            get {
                return ResourceManager.GetString("ipe_AddBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding data tag failed. Error: {0}.
        /// </summary>
        internal static string ipe_AddDataTagError {
            get {
                return ResourceManager.GetString("ipe_AddDataTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding for-each tag failed. Error: {0}.
        /// </summary>
        internal static string ipe_AddForechTagError {
            get {
                return ResourceManager.GetString("ipe_AddForechTagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding internal bookmark item failed. Error: {0}.
        /// </summary>
        internal static string ipe_AddIbmItemError {
            get {
                return ResourceManager.GetString("ipe_AddIbmItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding usc item failed. Error: {0}.
        /// </summary>
        internal static string ipe_AddUSCItemError {
            get {
                return ResourceManager.GetString("ipe_AddUSCItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_AddWordBookmarkError {
            get {
                return ResourceManager.GetString("ipe_AddWordBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding data into tree failed. Error: {0}.
        /// </summary>
        internal static string ipe_BindTreeError {
            get {
                return ResourceManager.GetString("ipe_BindTreeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing domain failed. Error: {0}.
        /// </summary>
        internal static string ipe_ChangeDomainError {
            get {
                return ResourceManager.GetString("ipe_ChangeDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing font failed. Error: {0}.
        /// </summary>
        internal static string ipe_ChangeFontError {
            get {
                return ResourceManager.GetString("ipe_ChangeFontError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking internal bookmark with word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_CheckIbmAndWbmError {
            get {
                return ResourceManager.GetString("ipe_CheckIbmAndWbmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking work bookmark with datasegment failed. Error: {0}.
        /// </summary>
        internal static string ipe_CheckWbmWithDatasegment {
            get {
                return ResourceManager.GetString("ipe_CheckWbmWithDatasegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking word struct failed. Error: {0}.
        /// </summary>
        internal static string ipe_CheckWordStructError {
            get {
                return ResourceManager.GetString("ipe_CheckWordStructError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_DeleteBookmarkError {
            get {
                return ResourceManager.GetString("ipe_DeleteBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating checksum failed. Error: {0}.
        /// </summary>
        internal static string ipe_GenChecksumError {
            get {
                return ResourceManager.GetString("ipe_GenChecksumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating image failed. Error: {0}.
        /// </summary>
        internal static string ipe_GenerateImageError {
            get {
                return ResourceManager.GetString("ipe_GenerateImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating osql failed. Error: {0}.
        /// </summary>
        internal static string ipe_GenOsqlError {
            get {
                return ResourceManager.GetString("ipe_GenOsqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating xslt failed. Error: {0}.
        /// </summary>
        internal static string ipe_GenXsltError {
            get {
                return ResourceManager.GetString("ipe_GenXsltError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting checksum failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetChecksumError {
            get {
                return ResourceManager.GetString("ipe_GetChecksumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting distinct bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetDistinctBookmarkError {
            get {
                return ResourceManager.GetString("ipe_GetDistinctBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting internal bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetInternalBookmarkError {
            get {
                return ResourceManager.GetString("ipe_GetInternalBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list domain failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetListDomainError {
            get {
                return ResourceManager.GetString("ipe_GetListDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting pdw information failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetPdwInfoError {
            get {
                return ResourceManager.GetString("ipe_GetPdwInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting plugin information failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetPluginInfoError {
            get {
                return ResourceManager.GetString("ipe_GetPluginInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting word body xml failed. Error: Can not get the word body content.
        /// </summary>
        internal static string ipe_GetWordBodyOuterXml {
            get {
                return ResourceManager.GetString("ipe_GetWordBodyOuterXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting word bookmark order by position failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetWordBookmarkByPositionError {
            get {
                return ResourceManager.GetString("ipe_GetWordBookmarkByPositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting word bookmarks failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetWordBookmarksError {
            get {
                return ResourceManager.GetString("ipe_GetWordBookmarksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting xsl content failed. Error: {0}.
        /// </summary>
        internal static string ipe_GetXslContentError {
            get {
                return ResourceManager.GetString("ipe_GetXslContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_HighlightBookmarkError {
            get {
                return ResourceManager.GetString("ipe_HighlightBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find datasegment.
        /// </summary>
        internal static string ipe_LoadDatasegmentError {
            get {
                return ResourceManager.GetString("ipe_LoadDatasegmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading domain data failed. Error: {0}.
        /// </summary>
        internal static string ipe_LoadDomainDataError {
            get {
                return ResourceManager.GetString("ipe_LoadDomainDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading internal bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_LoadInternalBookmarkError {
            get {
                return ResourceManager.GetString("ipe_LoadInternalBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resource failed. Error: {0}.
        /// </summary>
        internal static string ipe_LoadResourceError {
            get {
                return ResourceManager.GetString("ipe_LoadResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Name is blank.
        /// </summary>
        internal static string ipe_M001 {
            get {
                return ResourceManager.GetString("ipe_M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Name is existed.
        /// </summary>
        internal static string ipe_M002 {
            get {
                return ResourceManager.GetString("ipe_M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not existed.
        /// </summary>
        internal static string ipe_M005 {
            get {
                return ResourceManager.GetString("ipe_M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty expression.
        /// </summary>
        internal static string ipe_M007 {
            get {
                return ResourceManager.GetString("ipe_M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition must return true or false.
        /// </summary>
        internal static string ipe_M008 {
            get {
                return ResourceManager.GetString("ipe_M008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression.
        /// </summary>
        internal static string ipe_M009 {
            get {
                return ResourceManager.GetString("ipe_M009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesnot exist.
        /// </summary>
        internal static string ipe_M010 {
            get {
                return ResourceManager.GetString("ipe_M010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ProntoDoc template structure.
        /// </summary>
        internal static string ipe_NotIsProntoDoc {
            get {
                return ResourceManager.GetString("ipe_NotIsProntoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data and highlighted.
        /// </summary>
        internal static string ipe_NotSaveMessage {
            get {
                return ResourceManager.GetString("ipe_NotSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening document failed. Error: {0}.
        /// </summary>
        internal static string ipe_OpenDocumentError {
            get {
                return ResourceManager.GetString("ipe_OpenDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening pdwr failed. Error: {0}.
        /// </summary>
        internal static string ipe_OpenPdwrError {
            get {
                return ResourceManager.GetString("ipe_OpenPdwrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protecing word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_ProtectBookmarkError {
            get {
                return ResourceManager.GetString("ipe_ProtectBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protecting document failed. Error: {0}.
        /// </summary>
        internal static string ipe_ProtectDocumentError {
            get {
                return ResourceManager.GetString("ipe_ProtectDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recontructing failed. Error: {0}.
        /// </summary>
        internal static string ipe_ReconstructError {
            get {
                return ResourceManager.GetString("ipe_ReconstructError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing usc item failed. Error: {0}.
        /// </summary>
        internal static string ipe_RemoveUSCItemError {
            get {
                return ResourceManager.GetString("ipe_RemoveUSCItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing word struct failed. Error: {0}.
        /// </summary>
        internal static string ipe_RepairWordStructError {
            get {
                return ResourceManager.GetString("ipe_RepairWordStructError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving document failed. Error: {0}.
        /// </summary>
        internal static string ipe_SaveDocumentError {
            get {
                return ResourceManager.GetString("ipe_SaveDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving temporary file failed. Error: {0}.
        /// </summary>
        internal static string ipe_SaveFileError {
            get {
                return ResourceManager.GetString("ipe_SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving internal bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_SaveInternalBookmarkError {
            get {
                return ResourceManager.GetString("ipe_SaveInternalBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving pdw failed. Error: {0}.
        /// </summary>
        internal static string ipe_SavePdwError {
            get {
                return ResourceManager.GetString("ipe_SavePdwError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving pdw information failed. Error: {0}.
        /// </summary>
        internal static string ipe_SavePdwInfoError {
            get {
                return ResourceManager.GetString("ipe_SavePdwInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting usc item failed. Error: {0}.
        /// </summary>
        internal static string ipe_SelectUSCItemError {
            get {
                return ResourceManager.GetString("ipe_SelectUSCItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending mail failed. Error: {0}.
        /// </summary>
        internal static string ipe_SendMailError {
            get {
                return ResourceManager.GetString("ipe_SendMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending outlook mail failed. Error: {0}.
        /// </summary>
        internal static string ipe_SendOutlookMailError {
            get {
                return ResourceManager.GetString("ipe_SendOutlookMailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging usc item failed. Error: {0}.
        /// </summary>
        internal static string ipe_TagUSCItemError {
            get {
                return ResourceManager.GetString("ipe_TagUSCItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-highlighting word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_UnHighlightWordBookmarkError {
            get {
                return ResourceManager.GetString("ipe_UnHighlightWordBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-protecing word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_UnProtectBookmarkError {
            get {
                return ResourceManager.GetString("ipe_UnProtectBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-protecting document failed. Error: {0}.
        /// </summary>
        internal static string ipe_UnProtectDocumentError {
            get {
                return ResourceManager.GetString("ipe_UnProtectDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udating internal bookmark item failed. Error: {0}.
        /// </summary>
        internal static string ipe_UpdateIbmItemError {
            get {
                return ResourceManager.GetString("ipe_UpdateIbmItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating ribbon UI failed. Error: {0}.
        /// </summary>
        internal static string ipe_UpdateRibbonUIError {
            get {
                return ResourceManager.GetString("ipe_UpdateRibbonUIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating status bar failed. Error: {0}.
        /// </summary>
        internal static string ipe_UpdateStatusBarError {
            get {
                return ResourceManager.GetString("ipe_UpdateStatusBarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updateing USC item failed. Error: {0}.
        /// </summary>
        internal static string ipe_UpdateUSCItemError {
            get {
                return ResourceManager.GetString("ipe_UpdateUSCItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_UpdateWordBookmarkError {
            get {
                return ResourceManager.GetString("ipe_UpdateWordBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validateing checksum failed. Error: {0}.
        /// </summary>
        internal static string ipe_ValidateChecksumError {
            get {
                return ResourceManager.GetString("ipe_ValidateChecksumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validateing internal bookmarks failed. Error: {0}.
        /// </summary>
        internal static string ipe_ValidateIbmsError {
            get {
                return ResourceManager.GetString("ipe_ValidateIbmsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating internal bookmark with domain failed. Error: {0}.
        /// </summary>
        internal static string ipe_ValidateIbmWithDomainError {
            get {
                return ResourceManager.GetString("ipe_ValidateIbmWithDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data item and highlighted.
        /// </summary>
        internal static string ipe_ValidateMessage {
            get {
                return ResourceManager.GetString("ipe_ValidateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating file struct failed. Error: {0}.
        /// </summary>
        internal static string ipe_ValidateStructError {
            get {
                return ResourceManager.GetString("ipe_ValidateStructError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validateing word bookmark failed. Error: {0}.
        /// </summary>
        internal static string ipe_ValidateWordBookmarkError {
            get {
                return ResourceManager.GetString("ipe_ValidateWordBookmarkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validateing word bookmark with domain failed. Error: {0}.
        /// </summary>
        internal static string ipe_ValidateWordBookmarkWithDomainError {
            get {
                return ResourceManager.GetString("ipe_ValidateWordBookmarkWithDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating ProntoDoc template {0}.
        /// </summary>
        internal static string ipm_CheckingMessage {
            get {
                return ResourceManager.GetString("ipm_CheckingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ipm_ConfirmCaption {
            get {
                return ResourceManager.GetString("ipm_ConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProntoDoc for Word Template {0} is incorrect. Do you want to auto correct?.
        /// </summary>
        internal static string ipm_ConfirmMessage {
            get {
                return ResourceManager.GetString("ipm_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProntoDoc for Word.
        /// </summary>
        internal static string ipm_DescriptionFile {
            get {
                return ResourceManager.GetString("ipm_DescriptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string ipm_DialogSaveTitle {
            get {
                return ResourceManager.GetString("ipm_DialogSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spurious tag .
        /// </summary>
        internal static string ipm_ExceptionErrorPredix {
            get {
                return ResourceManager.GetString("ipm_ExceptionErrorPredix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProntoDoc template {0} loaded.
        /// </summary>
        internal static string ipm_FinishLoading {
            get {
                return ResourceManager.GetString("ipm_FinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding document-specific condition failed. Error: {0}.
        /// </summary>
        internal static string ipm_M001 {
            get {
                return ResourceManager.GetString("ipm_M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added.
        /// </summary>
        internal static string ipm_M004 {
            get {
                return ResourceManager.GetString("ipm_M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating ProntoDoc template failed. Error: {0}.
        /// </summary>
        internal static string ipm_M005 {
            get {
                return ResourceManager.GetString("ipm_M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProntoDoc template {0} saved.
        /// </summary>
        internal static string ipm_M006 {
            get {
                return ResourceManager.GetString("ipm_M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string ipm_mnuDeleteAll {
            get {
                return ResourceManager.GetString("ipm_mnuDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Current.
        /// </summary>
        internal static string ipm_mnuDeleteCurrent {
            get {
                return ResourceManager.GetString("ipm_mnuDeleteCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go First.
        /// </summary>
        internal static string ipm_mnuGoFirst {
            get {
                return ResourceManager.GetString("ipm_mnuGoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Last.
        /// </summary>
        internal static string ipm_mnuGoLast {
            get {
                return ResourceManager.GetString("ipm_mnuGoLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Previous.
        /// </summary>
        internal static string ipm_mnuGoPrevious {
            get {
                return ResourceManager.GetString("ipm_mnuGoPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Next.
        /// </summary>
        internal static string ipm_mnuGotoNext {
            get {
                return ResourceManager.GetString("ipm_mnuGotoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight All.
        /// </summary>
        internal static string ipm_mnuHighlightAll {
            get {
                return ResourceManager.GetString("ipm_mnuHighlightAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight First.
        /// </summary>
        internal static string ipm_mnuHighlightFirst {
            get {
                return ResourceManager.GetString("ipm_mnuHighlightFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Last.
        /// </summary>
        internal static string ipm_mnuHighlightLast {
            get {
                return ResourceManager.GetString("ipm_mnuHighlightLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Next.
        /// </summary>
        internal static string ipm_mnuHighlightNext {
            get {
                return ResourceManager.GetString("ipm_mnuHighlightNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Previous.
        /// </summary>
        internal static string ipm_mnuHighlightPrevious {
            get {
                return ResourceManager.GetString("ipm_mnuHighlightPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal of about.
        /// </summary>
        internal static string ipm_NoChooseDomain {
            get {
                return ResourceManager.GetString("ipm_NoChooseDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving ProntoDoc template failed. Error: {0}.
        /// </summary>
        internal static string ipm_NotIsProntoDoc {
            get {
                return ResourceManager.GetString("ipm_NotIsProntoDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define order by.
        /// </summary>
        internal static string ipm_OrderByMenuCaption {
            get {
                return ResourceManager.GetString("ipm_OrderByMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string ipm_RibbonBtnHide {
            get {
                return ResourceManager.GetString("ipm_RibbonBtnHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string ipm_RibbonBtnShow {
            get {
                return ResourceManager.GetString("ipm_RibbonBtnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProntoDoc.
        /// </summary>
        internal static string ipm_RibbonTitle {
            get {
                return ResourceManager.GetString("ipm_RibbonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to auto delete them?.
        /// </summary>
        internal static string ipm_SaveConfirmMessage {
            get {
                return ResourceManager.GetString("ipm_SaveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save notify message for document: {0}.
        /// </summary>
        internal static string ipm_SaveNotifyCaption {
            get {
                return ResourceManager.GetString("ipm_SaveNotifyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some data item is redundant and highlighted.
        /// </summary>
        internal static string ipm_SaveNotifyMessage {
            get {
                return ResourceManager.GetString("ipm_SaveNotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProntoDoc template {0} saved.
        /// </summary>
        internal static string ipm_SaveSuccessful {
            get {
                return ResourceManager.GetString("ipm_SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ipm_TooltipHeader {
            get {
                return ResourceManager.GetString("ipm_TooltipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The bookmark is not correct. Refer to highlighted text..
        /// </summary>
        internal static string ipm_WrongBookmarkMessages {
            get {
                return ResourceManager.GetString("ipm_WrongBookmarkMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The checksum is wrong..
        /// </summary>
        internal static string ipm_WrongChecksumMessage {
            get {
                return ResourceManager.GetString("ipm_WrongChecksumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The domain information is not correct. Refer to right panel..
        /// </summary>
        internal static string ipm_WrongDomainMessages {
            get {
                return ResourceManager.GetString("ipm_WrongDomainMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity error detected on this template.{0}Detail:.
        /// </summary>
        internal static string ipm_WrongMessages {
            get {
                return ResourceManager.GetString("ipm_WrongMessages", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon pdh {
            get {
                object obj = ResourceManager.GetObject("pdh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pdm {
            get {
                object obj = ResourceManager.GetObject("pdm", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .watermark
        ///{
        ///        top:30%;  
        ///        position: absolute;
        ///        font-size:2em;
        ///        color:#CCC;
        ///        width: 100%;
        ///        text-align: center;
        ///        z-index: 1000;
        ///        -webkit-transform:rotate(-30deg);
        ///        -moz-transform:rotate(-30deg);
        ///        -o-transform:rotate(-30deg);
        ///        transform:rotate(-30deg);
        ///        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=0);
        ///        opacity: 0.25;
        ///}.
        /// </summary>
        internal static string Pdm_WartermarkStyle {
            get {
                return ResourceManager.GetString("Pdm_WartermarkStyle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon pdw {
            get {
                object obj = ResourceManager.GetObject("pdw", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon pdz {
            get {
                object obj = ResourceManager.GetObject("pdz", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preview {
            get {
                object obj = ResourceManager.GetObject("Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallToBigFont {
            get {
                object obj = ResourceManager.GetObject("SmallToBigFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toggled {
            get {
                object obj = ResourceManager.GetObject("toggled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap untoggle {
            get {
                object obj = ResourceManager.GetObject("untoggle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
