package com.station.moudles.vo.search;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table warning_info  基站报警表
 *
 * @zdmgenerated 2017-47-24 07:47
 */
@ApiModel(value="基站报警表查询",description="基站报警表查询描述")
public class SearchWarningInfoPagingVo extends PageEntity {
    /**
     * This field corresponds to the database column warning_info.id  
     */
    @ApiModelProperty(value="pk",required=false)
    private Integer id;

    /**
     * This field corresponds to the database column warning_info.gprs_id  
     */
    @ApiModelProperty(value="gprsId",example="gprsId",required=false)
    private String gprsId;

    /**
     * This field corresponds to the database column warning_info.rcv_time  
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @ApiModelProperty(value="rcvTime")
    private Date rcvTime;

    /**
     * This field corresponds to the database column warning_info.cell_tem_high  单体温度过高
     */
    @ApiModelProperty(value="单体温度过高",required=false)
    private Byte cellTemHigh;

    /**
     * This field corresponds to the database column warning_info.env_tem_high  环境温度过高
     */
    @ApiModelProperty(value="环境温度过高",required=false)
    private Byte envTemHigh;

    /**
     * This field corresponds to the database column warning_info.cell_tem_low  单体温度过低
     */
    @ApiModelProperty(value="单体温度过低",required=false)
    private Byte cellTemLow;

    /**
     * This field corresponds to the database column warning_info.env_tem_low  环境温度过低
     */
    @ApiModelProperty(value="环境温度过低",required=false)
    private Byte envTemLow;

    /**
     * This field corresponds to the database column warning_info.gen_vol_high  总电压过压
     */
    @ApiModelProperty(value="总电压过压",required=false)
    private Byte genVolHigh;

    /**
     * This field corresponds to the database column warning_info.gen_vol_low  总电压欠压
     */
    @ApiModelProperty(value="总电压欠压",required=false)
    private Byte genVolLow;

    /**
     * This field corresponds to the database column warning_info.loss_electricity  掉电告警
     */
    @ApiModelProperty(value="掉电告警",required=false)
    private Byte lossElectricity;

    /**
     * This field corresponds to the database column warning_info.soc_low  SOC过低告警
     */
    @ApiModelProperty(value="SOC过低告警",required=false)
    private Byte socLow;
    
    @ApiModelProperty(value="三级公司id",required=false)
    private Integer companyId3;
    
    public Integer getCompanyId3() {
		return companyId3;
	}

	public void setCompanyId3(Integer companyId3) {
		this.companyId3 = companyId3;
	}

	/**
     * This method returns the value of the database column warning_info.id  
     * @return the value of warning_info.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the value of the database column warning_info.id  
     * @param id the value for warning_info.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column warning_info.gprs_id  
     * @return the value of warning_info.gprs_id
     */
    public String getGprsId() {
        return gprsId;
    }

    /**
     * This method sets the value of the database column warning_info.gprs_id  
     * @param gprsId the value for warning_info.gprs_id
     */
    public void setGprsId(String gprsId) {
        this.gprsId = gprsId == null ? null : gprsId.trim();
    }

    /**
     * This method returns the value of the database column warning_info.rcv_time  
     * @return the value of warning_info.rcv_time
     */
    public Date getRcvTime() {
        return rcvTime;
    }

    /**
     * This method sets the value of the database column warning_info.rcv_time  
     * @param rcvTime the value for warning_info.rcv_time
     */
    public void setRcvTime(Date rcvTime) {
        this.rcvTime = rcvTime;
    }

    /**
     * This method returns the value of the database column warning_info.cell_tem_high  单体温度过高
     * @return the value of warning_info.cell_tem_high
     */
    public Byte getCellTemHigh() {
        return cellTemHigh;
    }

    /**
     * This method sets the value of the database column warning_info.cell_tem_high  单体温度过高
     * @param cellTemHigh the value for warning_info.cell_tem_high
     */
    public void setCellTemHigh(Byte cellTemHigh) {
        this.cellTemHigh = cellTemHigh;
    }

    /**
     * This method returns the value of the database column warning_info.env_tem_high  环境温度过高
     * @return the value of warning_info.env_tem_high
     */
    public Byte getEnvTemHigh() {
        return envTemHigh;
    }

    /**
     * This method sets the value of the database column warning_info.env_tem_high  环境温度过高
     * @param envTemHigh the value for warning_info.env_tem_high
     */
    public void setEnvTemHigh(Byte envTemHigh) {
        this.envTemHigh = envTemHigh;
    }

    /**
     * This method returns the value of the database column warning_info.cell_tem_low  单体温度过低
     * @return the value of warning_info.cell_tem_low
     */
    public Byte getCellTemLow() {
        return cellTemLow;
    }

    /**
     * This method sets the value of the database column warning_info.cell_tem_low  单体温度过低
     * @param cellTemLow the value for warning_info.cell_tem_low
     */
    public void setCellTemLow(Byte cellTemLow) {
        this.cellTemLow = cellTemLow;
    }

    /**
     * This method returns the value of the database column warning_info.env_tem_low  环境温度过低
     * @return the value of warning_info.env_tem_low
     */
    public Byte getEnvTemLow() {
        return envTemLow;
    }

    /**
     * This method sets the value of the database column warning_info.env_tem_low  环境温度过低
     * @param envTemLow the value for warning_info.env_tem_low
     */
    public void setEnvTemLow(Byte envTemLow) {
        this.envTemLow = envTemLow;
    }

    /**
     * This method returns the value of the database column warning_info.gen_vol_high  总电压过压
     * @return the value of warning_info.gen_vol_high
     */
    public Byte getGenVolHigh() {
        return genVolHigh;
    }

    /**
     * This method sets the value of the database column warning_info.gen_vol_high  总电压过压
     * @param genVolHigh the value for warning_info.gen_vol_high
     */
    public void setGenVolHigh(Byte genVolHigh) {
        this.genVolHigh = genVolHigh;
    }

    /**
     * This method returns the value of the database column warning_info.gen_vol_low  总电压欠压
     * @return the value of warning_info.gen_vol_low
     */
    public Byte getGenVolLow() {
        return genVolLow;
    }

    /**
     * This method sets the value of the database column warning_info.gen_vol_low  总电压欠压
     * @param genVolLow the value for warning_info.gen_vol_low
     */
    public void setGenVolLow(Byte genVolLow) {
        this.genVolLow = genVolLow;
    }

    /**
     * This method returns the value of the database column warning_info.loss_electricity  掉电告警
     * @return the value of warning_info.loss_electricity
     */
    public Byte getLossElectricity() {
        return lossElectricity;
    }

    /**
     * This method sets the value of the database column warning_info.loss_electricity  掉电告警
     * @param lossElectricity the value for warning_info.loss_electricity
     */
    public void setLossElectricity(Byte lossElectricity) {
        this.lossElectricity = lossElectricity;
    }

    /**
     * This method returns the value of the database column warning_info.soc_low  SOC过低告警
     * @return the value of warning_info.soc_low
     */
    public Byte getSocLow() {
        return socLow;
    }

    /**
     * This method sets the value of the database column warning_info.soc_low  SOC过低告警
     * @param socLow the value for warning_info.soc_low
     */
    public void setSocLow(Byte socLow) {
        this.socLow = socLow;
    }
}