package com.station.moudles.vo.search;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table gprs_config_read  gprs参数读取表
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value="gprs参数读取表查询",description="gprs参数读取表查询描述")
public class SearchGprsConfigReadPagingVo extends PageEntity {
    /**
     * This field corresponds to the database column gprs_config_read.id  
     */
    @ApiModelProperty(value="pk",required=false)
    private Integer id;

    /**
     * This field corresponds to the database column gprs_config_read.gprs_id  
     */
    @ApiModelProperty(value="gprsId",example="gprsId",required=false)
    private String gprsId;

    /**
     * This field corresponds to the database column gprs_config_read.read_done  
     */
    @ApiModelProperty(value="readDone",required=false)
    private Byte readDone;

    /**
     * This field corresponds to the database column gprs_config_read.read_time  
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @ApiModelProperty(value="readTime")
    private Date readTime;

    /**
     * This method returns the value of the database column gprs_config_read.id  
     * @return the value of gprs_config_read.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the value of the database column gprs_config_read.id  
     * @param id the value for gprs_config_read.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column gprs_config_read.gprs_id  
     * @return the value of gprs_config_read.gprs_id
     */
    public String getGprsId() {
        return gprsId;
    }

    /**
     * This method sets the value of the database column gprs_config_read.gprs_id  
     * @param gprsId the value for gprs_config_read.gprs_id
     */
    public void setGprsId(String gprsId) {
        this.gprsId = gprsId == null ? null : gprsId.trim();
    }

    /**
     * This method returns the value of the database column gprs_config_read.read_done  
     * @return the value of gprs_config_read.read_done
     */
    public Byte getReadDone() {
        return readDone;
    }

    /**
     * This method sets the value of the database column gprs_config_read.read_done  
     * @param readDone the value for gprs_config_read.read_done
     */
    public void setReadDone(Byte readDone) {
        this.readDone = readDone;
    }

    /**
     * This method returns the value of the database column gprs_config_read.read_time  
     * @return the value of gprs_config_read.read_time
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method sets the value of the database column gprs_config_read.read_time  
     * @param readTime the value for gprs_config_read.read_time
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }
}