package com.station.moudles.vo.search;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table cell_history_info  电池更换整治历史信息
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value="电池更换整治历史信息查询",description="电池更换整治历史信息查询描述")
public class SearchCellHistoryInfoPagingVo extends PageEntity {
    /**
     * This field corresponds to the database column cell_history_info.id  
     */
    @ApiModelProperty(value="pk",required=false)
    private Integer id;

    /**
     * This field corresponds to the database column cell_history_info.gprs_id  
     */
    @ApiModelProperty(value="gprsId",example="gprsId",required=false)
    private String gprsId;

    /**
     * This field corresponds to the database column cell_history_info.cell_number  
     */
    @ApiModelProperty(value="cellNumber",required=false)
    private Integer cellNumber;

    /**
     * This field corresponds to the database column cell_history_info.cell_type  
     */
    @ApiModelProperty(value="cellType",example="cellType",required=false)
    private String cellType;

    /**
     * This field corresponds to the database column cell_history_info.cell_plant  
     */
    @ApiModelProperty(value="cellPlant",example="cellPlant",required=false)
    private String cellPlant;

    /**
     * This field corresponds to the database column cell_history_info.change_log  
     */
    @ApiModelProperty(value="changeLog",example="changeLog",required=false)
    private String changeLog;

    /**
     * This field corresponds to the database column cell_history_info.update_time  
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @ApiModelProperty(value="updateTime")
    private Date updateTime;

    /**
     * This method returns the value of the database column cell_history_info.id  
     * @return the value of cell_history_info.id
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method sets the value of the database column cell_history_info.id  
     * @param id the value for cell_history_info.id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method returns the value of the database column cell_history_info.gprs_id  
     * @return the value of cell_history_info.gprs_id
     */
    public String getGprsId() {
        return gprsId;
    }

    /**
     * This method sets the value of the database column cell_history_info.gprs_id  
     * @param gprsId the value for cell_history_info.gprs_id
     */
    public void setGprsId(String gprsId) {
        this.gprsId = gprsId == null ? null : gprsId.trim();
    }

    /**
     * This method returns the value of the database column cell_history_info.cell_number  
     * @return the value of cell_history_info.cell_number
     */
    public Integer getCellNumber() {
        return cellNumber;
    }

    /**
     * This method sets the value of the database column cell_history_info.cell_number  
     * @param cellNumber the value for cell_history_info.cell_number
     */
    public void setCellNumber(Integer cellNumber) {
        this.cellNumber = cellNumber;
    }

    /**
     * This method returns the value of the database column cell_history_info.cell_type  
     * @return the value of cell_history_info.cell_type
     */
    public String getCellType() {
        return cellType;
    }

    /**
     * This method sets the value of the database column cell_history_info.cell_type  
     * @param cellType the value for cell_history_info.cell_type
     */
    public void setCellType(String cellType) {
        this.cellType = cellType == null ? null : cellType.trim();
    }

    /**
     * This method returns the value of the database column cell_history_info.cell_plant  
     * @return the value of cell_history_info.cell_plant
     */
    public String getCellPlant() {
        return cellPlant;
    }

    /**
     * This method sets the value of the database column cell_history_info.cell_plant  
     * @param cellPlant the value for cell_history_info.cell_plant
     */
    public void setCellPlant(String cellPlant) {
        this.cellPlant = cellPlant == null ? null : cellPlant.trim();
    }

    /**
     * This method returns the value of the database column cell_history_info.change_log  
     * @return the value of cell_history_info.change_log
     */
    public String getChangeLog() {
        return changeLog;
    }

    /**
     * This method sets the value of the database column cell_history_info.change_log  
     * @param changeLog the value for cell_history_info.change_log
     */
    public void setChangeLog(String changeLog) {
        this.changeLog = changeLog == null ? null : changeLog.trim();
    }

    /**
     * This method returns the value of the database column cell_history_info.update_time  
     * @return the value of cell_history_info.update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method sets the value of the database column cell_history_info.update_time  
     * @param updateTime the value for cell_history_info.update_time
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}