package com.station.moudles.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.station.moudles.entity.CityCode;
import com.station.moudles.service.CityCodeService;
import com.station.moudles.vo.AjaxResponse;

import io.swagger.annotations.ApiOperation;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table city_code  
 *
 * @zdmgenerated 2017-15-22 04:15
 */
@Controller
@RequestMapping(value = "/cityCode")
public class CityCodeController extends BaseController {
	@Autowired
	CityCodeService cityCodeSer;

	@RequestMapping(value = "/list", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "根据条件获取列表", notes = "返回列表")
	public AjaxResponse<List<CityCode>> getCityCodeList(@RequestBody CityCode cityCode) {
		List<CityCode> cityCodeList = cityCodeSer.selectListSelective(cityCode);
		AjaxResponse<List<CityCode>> ajaxResponse = new AjaxResponse<List<CityCode>>(cityCodeList);
		return ajaxResponse;
	}
}