package com.station.moudles.controller;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.station.common.Constant;
import com.station.common.utils.ReflectUtil;
import com.station.moudles.entity.GprsBalanceSend;
import com.station.moudles.entity.PackDataInfoLatest;
import com.station.moudles.service.GprsBalanceSendService;
import com.station.moudles.service.PackDataInfoLatestService;
import com.station.moudles.vo.AjaxResponse;

import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiImplicitParams;
import io.swagger.annotations.ApiOperation;

/**
 * This class was generated by Bill Generator. This class corresponds to the
 * database table gprs_balance_send 均衡控制指令发送表
 *
 * @zdmgenerated 2017-17-26 10:17
 */
@Controller
@RequestMapping(value = "/gprsBalanceSend")
public class GprsBalanceSendController extends BaseController {
	@Autowired
	GprsBalanceSendService gprsBalanceSendSer;
	@Autowired
	PackDataInfoLatestService packDataInfoLatestSer;

	@RequestMapping(value = "/save", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "新增均衡控制指令发送表	", notes = "新增均衡控制指令发送表	")
	@ApiImplicitParams(value = { @ApiImplicitParam(required = false, name = "id", paramType = "query") })
	public AjaxResponse<GprsBalanceSend> save(@RequestBody GprsBalanceSend gprsBalanceSend) {
		gprsBalanceSend.setId(null);
		AjaxResponse<GprsBalanceSend> ajaxResponse = new AjaxResponse<GprsBalanceSend>(Constant.RS_CODE_ERROR,
				"添加均衡控制指令发送表	出错！");
		request.setAttribute("ajaxResponse", ajaxResponse);
		gprsBalanceSendSer.save(gprsBalanceSend);
		ajaxResponse.setCode(Constant.RS_CODE_SUCCESS);
		ajaxResponse.setMsg("添加均衡控制指令发送表	成功！");
		return ajaxResponse;
	}

	@RequestMapping(value = "/send", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "根据pk更新均衡控制指令发送表	", notes = "根据pk更新均衡控制指令发送表	，属性为null的不更新")
	public AjaxResponse<Object> update(@RequestBody GprsBalanceSend gprsBalanceSend) {
		AjaxResponse<Object> ajaxResponse = new AjaxResponse<Object>(Constant.RS_CODE_ERROR, "修改均衡控制指令发送表	出错！");
		request.setAttribute("ajaxResponse", ajaxResponse);
		gprsBalanceSendSer.save(gprsBalanceSend);
		gprsBalanceSendSer.send(gprsBalanceSend);
		ajaxResponse.setCode(Constant.RS_CODE_SUCCESS);
		ajaxResponse.setMsg("修改均衡控制指令发送表	成功！");
		return ajaxResponse;
	}

	@RequestMapping(value = "/entity/{gprsId}", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "根据pk获取均衡控制指令发送表	", notes = "根据pk获取均衡控制指令发送表	")
	public AjaxResponse<Map<String, Object>> getEntity(@PathVariable String gprsId) {
		GprsBalanceSend queryGprsBalanceSend = new GprsBalanceSend();
		queryGprsBalanceSend.setGprsId(gprsId);
		queryGprsBalanceSend.setSendDone((byte) -1);
		List<GprsBalanceSend> gprsBalanceSendList = gprsBalanceSendSer.selectListSelective(queryGprsBalanceSend);
		// ---add---
		List<Integer> cellEqus = new ArrayList<>();
		PackDataInfoLatest queryPdi = new PackDataInfoLatest();
		queryPdi.setGprsId(gprsId);
		List<PackDataInfoLatest> pdiList = packDataInfoLatestSer.selectListSelective(queryPdi);
		if (pdiList.size() > 0) {
			PackDataInfoLatest packDataInfoLatest = pdiList.get(0);
			List<Object> cellEquList = ReflectUtil.getValueByStartsWith(packDataInfoLatest, "cellEqu");
			for (int i = 0; i < cellEquList.size(); i++) {
				int cellEqu = cellEquList.get(i) == null ? 0 : Integer.parseInt(cellEquList.get(i).toString());
				cellEqus.add(cellEqu);
			}
		} else {
			for (int i = 0; i < 24; i++) {
				cellEqus.add(0);
			}
		}
		Map<String, Object> result = new HashMap<>();
		result.put("balanceConfig", gprsBalanceSendList.size() > 0 ? gprsBalanceSendList.get(0) : null);
		result.put("realState", cellEqus);
		// ---end---
		// 泛型由 GprsBalanceSend 改为 Map
		AjaxResponse<Map<String, Object>> ajaxResponse = new AjaxResponse<Map<String, Object>>(Constant.RS_CODE_SUCCESS,
				"获取均衡控制指令发送表	成功！");
		ajaxResponse.setData(result);
		return ajaxResponse;
	}

	@RequestMapping(value = "/entity/send/{gprsId}", method = RequestMethod.POST)
	@ResponseBody
	@ApiOperation(value = "根据pk获取均衡控制指令发送表	", notes = "根据pk获取均衡控制指令发送表	")
	public AjaxResponse<GprsBalanceSend> getSendEntity(@PathVariable String gprsId) {

		GprsBalanceSend gprsBalanceSend = gprsBalanceSendSer.selectByGprs(gprsId);
		AjaxResponse<GprsBalanceSend> ajaxResponse = new AjaxResponse<GprsBalanceSend>(Constant.RS_CODE_SUCCESS,
				"获取均衡控制指令发送表成功！");
		ajaxResponse.setData(gprsBalanceSend);
		return ajaxResponse;
	}

}