package com.station.moudles.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table pack_data_expand  扩展数据是指需要从基础数据中计算得到的数据表。此表定期更新，每次查询取ID最高的那条数据
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value = "扩展数据是指需要从基础数据中计算得到的数据表。此表定期更新，每次查询取ID最高的那条数据", description = "扩展数据是指需要从基础数据中计算得到的数据表。此表定期更新，每次查询取ID最高的那条数据描述")
public class PackDataExpand {
	/**
	 * This field corresponds to the database column pack_data_expand.id  
	 */
	@ApiModelProperty(value = "pk", required = true)
	private Integer id;

	/**
	 * This field corresponds to the database column pack_data_expand.gprs_id  基站gprs ID
	 */
	@ApiModelProperty(value = "基站gprs ID", example = "基站gprs ID", required = false)
	private String gprsId;

	/**
	 * This field corresponds to the database column pack_data_expand.update_time  
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@ApiModelProperty(value = "updateTime")
	private Date updateTime;

	/**
	 * This field corresponds to the database column pack_data_expand.pack_cap_pred  电池组容量预测
	 */
	@ApiModelProperty(value = "电池组容量预测", required = false)
	private Integer packCapPred;

	/**
	 * This field corresponds to the database column pack_data_expand.pack_discharge_time_pred  电池组放点时长预测， 单位hr
	 */
	@ApiModelProperty(value = "电池组放点时长预测， 单位hr", required = false)
	private BigDecimal packDischargeTimePred;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_1  1号电池内阻
	 */
	@ApiModelProperty(value = "1号电池内阻", required = false)
	private BigDecimal cellResist1;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_2  
	 */
	@ApiModelProperty(value = "cellResist2", required = false)
	private BigDecimal cellResist2;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_3  
	 */
	@ApiModelProperty(value = "cellResist3", required = false)
	private BigDecimal cellResist3;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_4  
	 */
	@ApiModelProperty(value = "cellResist4", required = false)
	private BigDecimal cellResist4;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_5  
	 */
	@ApiModelProperty(value = "cellResist5", required = false)
	private BigDecimal cellResist5;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_6  
	 */
	@ApiModelProperty(value = "cellResist6", required = false)
	private BigDecimal cellResist6;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_7  
	 */
	@ApiModelProperty(value = "cellResist7", required = false)
	private BigDecimal cellResist7;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_8  
	 */
	@ApiModelProperty(value = "cellResist8", required = false)
	private BigDecimal cellResist8;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_9  
	 */
	@ApiModelProperty(value = "cellResist9", required = false)
	private BigDecimal cellResist9;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_10  
	 */
	@ApiModelProperty(value = "cellResist10", required = false)
	private BigDecimal cellResist10;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_11  
	 */
	@ApiModelProperty(value = "cellResist11", required = false)
	private BigDecimal cellResist11;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_12  
	 */
	@ApiModelProperty(value = "cellResist12", required = false)
	private BigDecimal cellResist12;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_13  
	 */
	@ApiModelProperty(value = "cellResist13", required = false)
	private BigDecimal cellResist13;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_14  
	 */
	@ApiModelProperty(value = "cellResist14", required = false)
	private BigDecimal cellResist14;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_15  
	 */
	@ApiModelProperty(value = "cellResist15", required = false)
	private BigDecimal cellResist15;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_16  
	 */
	@ApiModelProperty(value = "cellResist16", required = false)
	private BigDecimal cellResist16;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_17  
	 */
	@ApiModelProperty(value = "cellResist17", required = false)
	private BigDecimal cellResist17;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_18  
	 */
	@ApiModelProperty(value = "cellResist18", required = false)
	private BigDecimal cellResist18;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_19  
	 */
	@ApiModelProperty(value = "cellResist19", required = false)
	private BigDecimal cellResist19;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_20  
	 */
	@ApiModelProperty(value = "cellResist20", required = false)
	private BigDecimal cellResist20;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_21  
	 */
	@ApiModelProperty(value = "cellResist21", required = false)
	private BigDecimal cellResist21;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_22  
	 */
	@ApiModelProperty(value = "cellResist22", required = false)
	private BigDecimal cellResist22;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_23  
	 */
	@ApiModelProperty(value = "cellResist23", required = false)
	private BigDecimal cellResist23;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_resist_24  
	 */
	@ApiModelProperty(value = "cellResist24", required = false)
	private BigDecimal cellResist24;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_1  1号电池容量
	 */
	@ApiModelProperty(value = "1号电池容量", required = false)
	private BigDecimal cellCap1;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_2  
	 */
	@ApiModelProperty(value = "cellCap2", required = false)
	private BigDecimal cellCap2;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_3  
	 */
	@ApiModelProperty(value = "cellCap3", required = false)
	private BigDecimal cellCap3;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_4  
	 */
	@ApiModelProperty(value = "cellCap4", required = false)
	private BigDecimal cellCap4;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_5  
	 */
	@ApiModelProperty(value = "cellCap5", required = false)
	private BigDecimal cellCap5;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_6  
	 */
	@ApiModelProperty(value = "cellCap6", required = false)
	private BigDecimal cellCap6;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_7  
	 */
	@ApiModelProperty(value = "cellCap7", required = false)
	private BigDecimal cellCap7;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_8  
	 */
	@ApiModelProperty(value = "cellCap8", required = false)
	private BigDecimal cellCap8;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_9  
	 */
	@ApiModelProperty(value = "cellCap9", required = false)
	private BigDecimal cellCap9;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_10  
	 */
	@ApiModelProperty(value = "cellCap10", required = false)
	private BigDecimal cellCap10;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_11  
	 */
	@ApiModelProperty(value = "cellCap11", required = false)
	private BigDecimal cellCap11;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_12  
	 */
	@ApiModelProperty(value = "cellCap12", required = false)
	private BigDecimal cellCap12;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_13  
	 */
	@ApiModelProperty(value = "cellCap13", required = false)
	private BigDecimal cellCap13;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_14  
	 */
	@ApiModelProperty(value = "cellCap14", required = false)
	private BigDecimal cellCap14;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_15  
	 */
	@ApiModelProperty(value = "cellCap15", required = false)
	private BigDecimal cellCap15;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_16  
	 */
	@ApiModelProperty(value = "cellCap16", required = false)
	private BigDecimal cellCap16;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_17  
	 */
	@ApiModelProperty(value = "cellCap17", required = false)
	private BigDecimal cellCap17;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_18  
	 */
	@ApiModelProperty(value = "cellCap18", required = false)
	private BigDecimal cellCap18;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_19  
	 */
	@ApiModelProperty(value = "cellCap19", required = false)
	private BigDecimal cellCap19;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_20  
	 */
	@ApiModelProperty(value = "cellCap20", required = false)
	private BigDecimal cellCap20;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_21  
	 */
	@ApiModelProperty(value = "cellCap21", required = false)
	private BigDecimal cellCap21;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_22  
	 */
	@ApiModelProperty(value = "cellCap22", required = false)
	private BigDecimal cellCap22;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_23  
	 */
	@ApiModelProperty(value = "cellCap23", required = false)
	private BigDecimal cellCap23;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_cap_24  
	 */
	@ApiModelProperty(value = "cellCap24", required = false)
	private BigDecimal cellCap24;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_1  1号电池性能 0:正常,1:较差, 2: 故障
	 */
	@ApiModelProperty(value = "1号电池性能 0:正常,1:较差, 2: 故障", required = false)
	private Integer cellEvalu1;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_2  
	 */
	@ApiModelProperty(value = "cellEvalu2", required = false)
	private Integer cellEvalu2;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_3  
	 */
	@ApiModelProperty(value = "cellEvalu3", required = false)
	private Integer cellEvalu3;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_4  
	 */
	@ApiModelProperty(value = "cellEvalu4", required = false)
	private Integer cellEvalu4;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_5  
	 */
	@ApiModelProperty(value = "cellEvalu5", required = false)
	private Integer cellEvalu5;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_6  
	 */
	@ApiModelProperty(value = "cellEvalu6", required = false)
	private Integer cellEvalu6;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_7  
	 */
	@ApiModelProperty(value = "cellEvalu7", required = false)
	private Integer cellEvalu7;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_8  
	 */
	@ApiModelProperty(value = "cellEvalu8", required = false)
	private Integer cellEvalu8;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_9  
	 */
	@ApiModelProperty(value = "cellEvalu9", required = false)
	private Integer cellEvalu9;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_10  
	 */
	@ApiModelProperty(value = "cellEvalu10", required = false)
	private Integer cellEvalu10;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_11  
	 */
	@ApiModelProperty(value = "cellEvalu11", required = false)
	private Integer cellEvalu11;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_12  
	 */
	@ApiModelProperty(value = "cellEvalu12", required = false)
	private Integer cellEvalu12;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_13  
	 */
	@ApiModelProperty(value = "cellEvalu13", required = false)
	private Integer cellEvalu13;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_14  
	 */
	@ApiModelProperty(value = "cellEvalu14", required = false)
	private Integer cellEvalu14;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_15  
	 */
	@ApiModelProperty(value = "cellEvalu15", required = false)
	private Integer cellEvalu15;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_16  
	 */
	@ApiModelProperty(value = "cellEvalu16", required = false)
	private Integer cellEvalu16;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_17  
	 */
	@ApiModelProperty(value = "cellEvalu17", required = false)
	private Integer cellEvalu17;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_18  
	 */
	@ApiModelProperty(value = "cellEvalu18", required = false)
	private Integer cellEvalu18;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_19  
	 */
	@ApiModelProperty(value = "cellEvalu19", required = false)
	private Integer cellEvalu19;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_20  
	 */
	@ApiModelProperty(value = "cellEvalu20", required = false)
	private Integer cellEvalu20;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_21  
	 */
	@ApiModelProperty(value = "cellEvalu21", required = false)
	private Integer cellEvalu21;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_22  
	 */
	@ApiModelProperty(value = "cellEvalu22", required = false)
	private Integer cellEvalu22;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_23  
	 */
	@ApiModelProperty(value = "cellEvalu23", required = false)
	private Integer cellEvalu23;

	/**
	 * This field corresponds to the database column pack_data_expand.cell_evalu_24  
	 */
	@ApiModelProperty(value = "cellEvalu24", required = false)
	private Integer cellEvalu24;

    @ApiModelProperty(value = "cellCapSort1", required = false)
    private Integer cellCapSort1;

    @ApiModelProperty(value = "cellCapSort2", required = false)
    private Integer cellCapSort2;

    @ApiModelProperty(value = "cellCapSort3", required = false)
    private Integer cellCapSort3;

    @ApiModelProperty(value = "cellCapSort4", required = false)
    private Integer cellCapSort4;

    @ApiModelProperty(value = "cellCapSort5", required = false)
    private Integer cellCapSort5;

    @ApiModelProperty(value = "cellCapSort6", required = false)
    private Integer cellCapSort6;

    @ApiModelProperty(value = "cellCapSort7", required = false)
    private Integer cellCapSort7;

    @ApiModelProperty(value = "cellCapSort8", required = false)
    private Integer cellCapSort8;

    @ApiModelProperty(value = "cellCapSort9", required = false)
    private Integer cellCapSort9;

    @ApiModelProperty(value = "cellCapSort10", required = false)
    private Integer cellCapSort10;

    @ApiModelProperty(value = "cellCapSort11", required = false)
    private Integer cellCapSort11;

    @ApiModelProperty(value = "cellCapSort12", required = false)
    private Integer cellCapSort12;

    @ApiModelProperty(value = "cellCapSort13", required = false)
    private Integer cellCapSort13;

    @ApiModelProperty(value = "cellCapSort14", required = false)
    private Integer cellCapSort14;

    @ApiModelProperty(value = "cellCapSort15", required = false)
    private Integer cellCapSort15;

    @ApiModelProperty(value = "cellCapSort16", required = false)
    private Integer cellCapSort16;

    @ApiModelProperty(value = "cellCapSort17", required = false)
    private Integer cellCapSort17;

    @ApiModelProperty(value = "cellCapSort18", required = false)
    private Integer cellCapSort18;

    @ApiModelProperty(value = "cellCapSort19", required = false)
    private Integer cellCapSort19;

    @ApiModelProperty(value = "cellCapSort20", required = false)
    private Integer cellCapSort20;

    @ApiModelProperty(value = "cellCapSort21", required = false)
    private Integer cellCapSort21;

    @ApiModelProperty(value = "cellCapSort22", required = false)
    private Integer cellCapSort22;

    @ApiModelProperty(value = "cellCapSort23", required = false)
    private Integer cellCapSort23;

    @ApiModelProperty(value = "cellCapSort24", required = false)
    private Integer cellCapSort24;

    /**
     * This method returns the value of the database column pack_data_expand.id
     * @return the value of pack_data_expand.id
     */
    public Integer getId() {
        return id;
    }

	/**
	 * This method sets the value of the database column pack_data_expand.id  
	 * @param id the value for pack_data_expand.id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.gprs_id  基站gprs ID
	 * @return the value of pack_data_expand.gprs_id
	 */
	public String getGprsId() {
		return gprsId;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.gprs_id  基站gprs ID
	 * @param gprsId the value for pack_data_expand.gprs_id
	 */
	public void setGprsId(String gprsId) {
		this.gprsId = gprsId == null ? null : gprsId.trim();
	}

	/**
	 * This method returns the value of the database column pack_data_expand.update_time  
	 * @return the value of pack_data_expand.update_time
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.update_time  
	 * @param updateTime the value for pack_data_expand.update_time
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.pack_cap_pred  电池组容量预测
	 * @return the value of pack_data_expand.pack_cap_pred
	 */
	public Integer getPackCapPred() {
		return packCapPred;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.pack_cap_pred  电池组容量预测
	 * @param packCapPred the value for pack_data_expand.pack_cap_pred
	 */
	public void setPackCapPred(Integer packCapPred) {
		this.packCapPred = packCapPred;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.pack_discharge_time_pred  电池组放点时长预测， 单位hr
	 * @return the value of pack_data_expand.pack_discharge_time_pred
	 */
	public BigDecimal getPackDischargeTimePred() {
		return packDischargeTimePred;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.pack_discharge_time_pred  电池组放点时长预测， 单位hr
	 * @param packDischargeTimePred the value for pack_data_expand.pack_discharge_time_pred
	 */
	public void setPackDischargeTimePred(BigDecimal packDischargeTimePred) {
		this.packDischargeTimePred = packDischargeTimePred;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_1  1号电池内阻
	 * @return the value of pack_data_expand.cell_resist_1
	 */
	public BigDecimal getCellResist1() {
		return cellResist1;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_1  1号电池内阻
	 * @param cellResist1 the value for pack_data_expand.cell_resist_1
	 */
	public void setCellResist1(BigDecimal cellResist1) {
		this.cellResist1 = cellResist1;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_2  
	 * @return the value of pack_data_expand.cell_resist_2
	 */
	public BigDecimal getCellResist2() {
		return cellResist2;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_2  
	 * @param cellResist2 the value for pack_data_expand.cell_resist_2
	 */
	public void setCellResist2(BigDecimal cellResist2) {
		this.cellResist2 = cellResist2;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_3  
	 * @return the value of pack_data_expand.cell_resist_3
	 */
	public BigDecimal getCellResist3() {
		return cellResist3;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_3  
	 * @param cellResist3 the value for pack_data_expand.cell_resist_3
	 */
	public void setCellResist3(BigDecimal cellResist3) {
		this.cellResist3 = cellResist3;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_4  
	 * @return the value of pack_data_expand.cell_resist_4
	 */
	public BigDecimal getCellResist4() {
		return cellResist4;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_4  
	 * @param cellResist4 the value for pack_data_expand.cell_resist_4
	 */
	public void setCellResist4(BigDecimal cellResist4) {
		this.cellResist4 = cellResist4;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_5  
	 * @return the value of pack_data_expand.cell_resist_5
	 */
	public BigDecimal getCellResist5() {
		return cellResist5;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_5  
	 * @param cellResist5 the value for pack_data_expand.cell_resist_5
	 */
	public void setCellResist5(BigDecimal cellResist5) {
		this.cellResist5 = cellResist5;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_6  
	 * @return the value of pack_data_expand.cell_resist_6
	 */
	public BigDecimal getCellResist6() {
		return cellResist6;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_6  
	 * @param cellResist6 the value for pack_data_expand.cell_resist_6
	 */
	public void setCellResist6(BigDecimal cellResist6) {
		this.cellResist6 = cellResist6;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_7  
	 * @return the value of pack_data_expand.cell_resist_7
	 */
	public BigDecimal getCellResist7() {
		return cellResist7;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_7  
	 * @param cellResist7 the value for pack_data_expand.cell_resist_7
	 */
	public void setCellResist7(BigDecimal cellResist7) {
		this.cellResist7 = cellResist7;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_8  
	 * @return the value of pack_data_expand.cell_resist_8
	 */
	public BigDecimal getCellResist8() {
		return cellResist8;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_8  
	 * @param cellResist8 the value for pack_data_expand.cell_resist_8
	 */
	public void setCellResist8(BigDecimal cellResist8) {
		this.cellResist8 = cellResist8;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_9  
	 * @return the value of pack_data_expand.cell_resist_9
	 */
	public BigDecimal getCellResist9() {
		return cellResist9;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_9  
	 * @param cellResist9 the value for pack_data_expand.cell_resist_9
	 */
	public void setCellResist9(BigDecimal cellResist9) {
		this.cellResist9 = cellResist9;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_10  
	 * @return the value of pack_data_expand.cell_resist_10
	 */
	public BigDecimal getCellResist10() {
		return cellResist10;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_10  
	 * @param cellResist10 the value for pack_data_expand.cell_resist_10
	 */
	public void setCellResist10(BigDecimal cellResist10) {
		this.cellResist10 = cellResist10;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_11  
	 * @return the value of pack_data_expand.cell_resist_11
	 */
	public BigDecimal getCellResist11() {
		return cellResist11;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_11  
	 * @param cellResist11 the value for pack_data_expand.cell_resist_11
	 */
	public void setCellResist11(BigDecimal cellResist11) {
		this.cellResist11 = cellResist11;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_12  
	 * @return the value of pack_data_expand.cell_resist_12
	 */
	public BigDecimal getCellResist12() {
		return cellResist12;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_12  
	 * @param cellResist12 the value for pack_data_expand.cell_resist_12
	 */
	public void setCellResist12(BigDecimal cellResist12) {
		this.cellResist12 = cellResist12;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_13  
	 * @return the value of pack_data_expand.cell_resist_13
	 */
	public BigDecimal getCellResist13() {
		return cellResist13;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_13  
	 * @param cellResist13 the value for pack_data_expand.cell_resist_13
	 */
	public void setCellResist13(BigDecimal cellResist13) {
		this.cellResist13 = cellResist13;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_14  
	 * @return the value of pack_data_expand.cell_resist_14
	 */
	public BigDecimal getCellResist14() {
		return cellResist14;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_14  
	 * @param cellResist14 the value for pack_data_expand.cell_resist_14
	 */
	public void setCellResist14(BigDecimal cellResist14) {
		this.cellResist14 = cellResist14;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_15  
	 * @return the value of pack_data_expand.cell_resist_15
	 */
	public BigDecimal getCellResist15() {
		return cellResist15;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_15  
	 * @param cellResist15 the value for pack_data_expand.cell_resist_15
	 */
	public void setCellResist15(BigDecimal cellResist15) {
		this.cellResist15 = cellResist15;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_16  
	 * @return the value of pack_data_expand.cell_resist_16
	 */
	public BigDecimal getCellResist16() {
		return cellResist16;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_16  
	 * @param cellResist16 the value for pack_data_expand.cell_resist_16
	 */
	public void setCellResist16(BigDecimal cellResist16) {
		this.cellResist16 = cellResist16;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_17  
	 * @return the value of pack_data_expand.cell_resist_17
	 */
	public BigDecimal getCellResist17() {
		return cellResist17;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_17  
	 * @param cellResist17 the value for pack_data_expand.cell_resist_17
	 */
	public void setCellResist17(BigDecimal cellResist17) {
		this.cellResist17 = cellResist17;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_18  
	 * @return the value of pack_data_expand.cell_resist_18
	 */
	public BigDecimal getCellResist18() {
		return cellResist18;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_18  
	 * @param cellResist18 the value for pack_data_expand.cell_resist_18
	 */
	public void setCellResist18(BigDecimal cellResist18) {
		this.cellResist18 = cellResist18;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_19  
	 * @return the value of pack_data_expand.cell_resist_19
	 */
	public BigDecimal getCellResist19() {
		return cellResist19;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_19  
	 * @param cellResist19 the value for pack_data_expand.cell_resist_19
	 */
	public void setCellResist19(BigDecimal cellResist19) {
		this.cellResist19 = cellResist19;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_20  
	 * @return the value of pack_data_expand.cell_resist_20
	 */
	public BigDecimal getCellResist20() {
		return cellResist20;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_20  
	 * @param cellResist20 the value for pack_data_expand.cell_resist_20
	 */
	public void setCellResist20(BigDecimal cellResist20) {
		this.cellResist20 = cellResist20;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_21  
	 * @return the value of pack_data_expand.cell_resist_21
	 */
	public BigDecimal getCellResist21() {
		return cellResist21;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_21  
	 * @param cellResist21 the value for pack_data_expand.cell_resist_21
	 */
	public void setCellResist21(BigDecimal cellResist21) {
		this.cellResist21 = cellResist21;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_22  
	 * @return the value of pack_data_expand.cell_resist_22
	 */
	public BigDecimal getCellResist22() {
		return cellResist22;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_22  
	 * @param cellResist22 the value for pack_data_expand.cell_resist_22
	 */
	public void setCellResist22(BigDecimal cellResist22) {
		this.cellResist22 = cellResist22;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_23  
	 * @return the value of pack_data_expand.cell_resist_23
	 */
	public BigDecimal getCellResist23() {
		return cellResist23;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_23  
	 * @param cellResist23 the value for pack_data_expand.cell_resist_23
	 */
	public void setCellResist23(BigDecimal cellResist23) {
		this.cellResist23 = cellResist23;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_resist_24  
	 * @return the value of pack_data_expand.cell_resist_24
	 */
	public BigDecimal getCellResist24() {
		return cellResist24;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_resist_24  
	 * @param cellResist24 the value for pack_data_expand.cell_resist_24
	 */
	public void setCellResist24(BigDecimal cellResist24) {
		this.cellResist24 = cellResist24;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_1  1号电池容量
	 * @return the value of pack_data_expand.cell_cap_1
	 */
	public BigDecimal getCellCap1() {
		return cellCap1;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_1  1号电池容量
	 * @param cellCap1 the value for pack_data_expand.cell_cap_1
	 */
	public void setCellCap1(BigDecimal cellCap1) {
		this.cellCap1 = cellCap1;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_2  
	 * @return the value of pack_data_expand.cell_cap_2
	 */
	public BigDecimal getCellCap2() {
		return cellCap2;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_2  
	 * @param cellCap2 the value for pack_data_expand.cell_cap_2
	 */
	public void setCellCap2(BigDecimal cellCap2) {
		this.cellCap2 = cellCap2;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_3  
	 * @return the value of pack_data_expand.cell_cap_3
	 */
	public BigDecimal getCellCap3() {
		return cellCap3;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_3  
	 * @param cellCap3 the value for pack_data_expand.cell_cap_3
	 */
	public void setCellCap3(BigDecimal cellCap3) {
		this.cellCap3 = cellCap3;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_4  
	 * @return the value of pack_data_expand.cell_cap_4
	 */
	public BigDecimal getCellCap4() {
		return cellCap4;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_4  
	 * @param cellCap4 the value for pack_data_expand.cell_cap_4
	 */
	public void setCellCap4(BigDecimal cellCap4) {
		this.cellCap4 = cellCap4;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_5  
	 * @return the value of pack_data_expand.cell_cap_5
	 */
	public BigDecimal getCellCap5() {
		return cellCap5;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_5  
	 * @param cellCap5 the value for pack_data_expand.cell_cap_5
	 */
	public void setCellCap5(BigDecimal cellCap5) {
		this.cellCap5 = cellCap5;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_6  
	 * @return the value of pack_data_expand.cell_cap_6
	 */
	public BigDecimal getCellCap6() {
		return cellCap6;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_6  
	 * @param cellCap6 the value for pack_data_expand.cell_cap_6
	 */
	public void setCellCap6(BigDecimal cellCap6) {
		this.cellCap6 = cellCap6;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_7  
	 * @return the value of pack_data_expand.cell_cap_7
	 */
	public BigDecimal getCellCap7() {
		return cellCap7;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_7  
	 * @param cellCap7 the value for pack_data_expand.cell_cap_7
	 */
	public void setCellCap7(BigDecimal cellCap7) {
		this.cellCap7 = cellCap7;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_8  
	 * @return the value of pack_data_expand.cell_cap_8
	 */
	public BigDecimal getCellCap8() {
		return cellCap8;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_8  
	 * @param cellCap8 the value for pack_data_expand.cell_cap_8
	 */
	public void setCellCap8(BigDecimal cellCap8) {
		this.cellCap8 = cellCap8;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_9  
	 * @return the value of pack_data_expand.cell_cap_9
	 */
	public BigDecimal getCellCap9() {
		return cellCap9;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_9  
	 * @param cellCap9 the value for pack_data_expand.cell_cap_9
	 */
	public void setCellCap9(BigDecimal cellCap9) {
		this.cellCap9 = cellCap9;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_10  
	 * @return the value of pack_data_expand.cell_cap_10
	 */
	public BigDecimal getCellCap10() {
		return cellCap10;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_10  
	 * @param cellCap10 the value for pack_data_expand.cell_cap_10
	 */
	public void setCellCap10(BigDecimal cellCap10) {
		this.cellCap10 = cellCap10;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_11  
	 * @return the value of pack_data_expand.cell_cap_11
	 */
	public BigDecimal getCellCap11() {
		return cellCap11;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_11  
	 * @param cellCap11 the value for pack_data_expand.cell_cap_11
	 */
	public void setCellCap11(BigDecimal cellCap11) {
		this.cellCap11 = cellCap11;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_12  
	 * @return the value of pack_data_expand.cell_cap_12
	 */
	public BigDecimal getCellCap12() {
		return cellCap12;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_12  
	 * @param cellCap12 the value for pack_data_expand.cell_cap_12
	 */
	public void setCellCap12(BigDecimal cellCap12) {
		this.cellCap12 = cellCap12;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_13  
	 * @return the value of pack_data_expand.cell_cap_13
	 */
	public BigDecimal getCellCap13() {
		return cellCap13;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_13  
	 * @param cellCap13 the value for pack_data_expand.cell_cap_13
	 */
	public void setCellCap13(BigDecimal cellCap13) {
		this.cellCap13 = cellCap13;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_14  
	 * @return the value of pack_data_expand.cell_cap_14
	 */
	public BigDecimal getCellCap14() {
		return cellCap14;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_14  
	 * @param cellCap14 the value for pack_data_expand.cell_cap_14
	 */
	public void setCellCap14(BigDecimal cellCap14) {
		this.cellCap14 = cellCap14;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_15  
	 * @return the value of pack_data_expand.cell_cap_15
	 */
	public BigDecimal getCellCap15() {
		return cellCap15;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_15  
	 * @param cellCap15 the value for pack_data_expand.cell_cap_15
	 */
	public void setCellCap15(BigDecimal cellCap15) {
		this.cellCap15 = cellCap15;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_16  
	 * @return the value of pack_data_expand.cell_cap_16
	 */
	public BigDecimal getCellCap16() {
		return cellCap16;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_16  
	 * @param cellCap16 the value for pack_data_expand.cell_cap_16
	 */
	public void setCellCap16(BigDecimal cellCap16) {
		this.cellCap16 = cellCap16;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_17  
	 * @return the value of pack_data_expand.cell_cap_17
	 */
	public BigDecimal getCellCap17() {
		return cellCap17;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_17  
	 * @param cellCap17 the value for pack_data_expand.cell_cap_17
	 */
	public void setCellCap17(BigDecimal cellCap17) {
		this.cellCap17 = cellCap17;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_18  
	 * @return the value of pack_data_expand.cell_cap_18
	 */
	public BigDecimal getCellCap18() {
		return cellCap18;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_18  
	 * @param cellCap18 the value for pack_data_expand.cell_cap_18
	 */
	public void setCellCap18(BigDecimal cellCap18) {
		this.cellCap18 = cellCap18;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_19  
	 * @return the value of pack_data_expand.cell_cap_19
	 */
	public BigDecimal getCellCap19() {
		return cellCap19;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_19  
	 * @param cellCap19 the value for pack_data_expand.cell_cap_19
	 */
	public void setCellCap19(BigDecimal cellCap19) {
		this.cellCap19 = cellCap19;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_20  
	 * @return the value of pack_data_expand.cell_cap_20
	 */
	public BigDecimal getCellCap20() {
		return cellCap20;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_20  
	 * @param cellCap20 the value for pack_data_expand.cell_cap_20
	 */
	public void setCellCap20(BigDecimal cellCap20) {
		this.cellCap20 = cellCap20;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_21  
	 * @return the value of pack_data_expand.cell_cap_21
	 */
	public BigDecimal getCellCap21() {
		return cellCap21;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_21  
	 * @param cellCap21 the value for pack_data_expand.cell_cap_21
	 */
	public void setCellCap21(BigDecimal cellCap21) {
		this.cellCap21 = cellCap21;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_22  
	 * @return the value of pack_data_expand.cell_cap_22
	 */
	public BigDecimal getCellCap22() {
		return cellCap22;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_22  
	 * @param cellCap22 the value for pack_data_expand.cell_cap_22
	 */
	public void setCellCap22(BigDecimal cellCap22) {
		this.cellCap22 = cellCap22;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_23  
	 * @return the value of pack_data_expand.cell_cap_23
	 */
	public BigDecimal getCellCap23() {
		return cellCap23;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_23  
	 * @param cellCap23 the value for pack_data_expand.cell_cap_23
	 */
	public void setCellCap23(BigDecimal cellCap23) {
		this.cellCap23 = cellCap23;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_cap_24  
	 * @return the value of pack_data_expand.cell_cap_24
	 */
	public BigDecimal getCellCap24() {
		return cellCap24;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_cap_24  
	 * @param cellCap24 the value for pack_data_expand.cell_cap_24
	 */
	public void setCellCap24(BigDecimal cellCap24) {
		this.cellCap24 = cellCap24;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_1  1号电池性能 0:正常,1:较差, 2: 故障
	 * @return the value of pack_data_expand.cell_evalu_1
	 */
	public Integer getCellEvalu1() {
		return cellEvalu1;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_1  1号电池性能 0:正常,1:较差, 2: 故障
	 * @param cellEvalu1 the value for pack_data_expand.cell_evalu_1
	 */
	public void setCellEvalu1(Integer cellEvalu1) {
		this.cellEvalu1 = cellEvalu1;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_2  
	 * @return the value of pack_data_expand.cell_evalu_2
	 */
	public Integer getCellEvalu2() {
		return cellEvalu2;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_2  
	 * @param cellEvalu2 the value for pack_data_expand.cell_evalu_2
	 */
	public void setCellEvalu2(Integer cellEvalu2) {
		this.cellEvalu2 = cellEvalu2;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_3  
	 * @return the value of pack_data_expand.cell_evalu_3
	 */
	public Integer getCellEvalu3() {
		return cellEvalu3;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_3  
	 * @param cellEvalu3 the value for pack_data_expand.cell_evalu_3
	 */
	public void setCellEvalu3(Integer cellEvalu3) {
		this.cellEvalu3 = cellEvalu3;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_4  
	 * @return the value of pack_data_expand.cell_evalu_4
	 */
	public Integer getCellEvalu4() {
		return cellEvalu4;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_4  
	 * @param cellEvalu4 the value for pack_data_expand.cell_evalu_4
	 */
	public void setCellEvalu4(Integer cellEvalu4) {
		this.cellEvalu4 = cellEvalu4;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_5  
	 * @return the value of pack_data_expand.cell_evalu_5
	 */
	public Integer getCellEvalu5() {
		return cellEvalu5;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_5  
	 * @param cellEvalu5 the value for pack_data_expand.cell_evalu_5
	 */
	public void setCellEvalu5(Integer cellEvalu5) {
		this.cellEvalu5 = cellEvalu5;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_6  
	 * @return the value of pack_data_expand.cell_evalu_6
	 */
	public Integer getCellEvalu6() {
		return cellEvalu6;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_6  
	 * @param cellEvalu6 the value for pack_data_expand.cell_evalu_6
	 */
	public void setCellEvalu6(Integer cellEvalu6) {
		this.cellEvalu6 = cellEvalu6;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_7  
	 * @return the value of pack_data_expand.cell_evalu_7
	 */
	public Integer getCellEvalu7() {
		return cellEvalu7;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_7  
	 * @param cellEvalu7 the value for pack_data_expand.cell_evalu_7
	 */
	public void setCellEvalu7(Integer cellEvalu7) {
		this.cellEvalu7 = cellEvalu7;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_8  
	 * @return the value of pack_data_expand.cell_evalu_8
	 */
	public Integer getCellEvalu8() {
		return cellEvalu8;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_8  
	 * @param cellEvalu8 the value for pack_data_expand.cell_evalu_8
	 */
	public void setCellEvalu8(Integer cellEvalu8) {
		this.cellEvalu8 = cellEvalu8;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_9  
	 * @return the value of pack_data_expand.cell_evalu_9
	 */
	public Integer getCellEvalu9() {
		return cellEvalu9;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_9  
	 * @param cellEvalu9 the value for pack_data_expand.cell_evalu_9
	 */
	public void setCellEvalu9(Integer cellEvalu9) {
		this.cellEvalu9 = cellEvalu9;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_10  
	 * @return the value of pack_data_expand.cell_evalu_10
	 */
	public Integer getCellEvalu10() {
		return cellEvalu10;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_10  
	 * @param cellEvalu10 the value for pack_data_expand.cell_evalu_10
	 */
	public void setCellEvalu10(Integer cellEvalu10) {
		this.cellEvalu10 = cellEvalu10;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_11  
	 * @return the value of pack_data_expand.cell_evalu_11
	 */
	public Integer getCellEvalu11() {
		return cellEvalu11;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_11  
	 * @param cellEvalu11 the value for pack_data_expand.cell_evalu_11
	 */
	public void setCellEvalu11(Integer cellEvalu11) {
		this.cellEvalu11 = cellEvalu11;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_12  
	 * @return the value of pack_data_expand.cell_evalu_12
	 */
	public Integer getCellEvalu12() {
		return cellEvalu12;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_12  
	 * @param cellEvalu12 the value for pack_data_expand.cell_evalu_12
	 */
	public void setCellEvalu12(Integer cellEvalu12) {
		this.cellEvalu12 = cellEvalu12;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_13  
	 * @return the value of pack_data_expand.cell_evalu_13
	 */
	public Integer getCellEvalu13() {
		return cellEvalu13;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_13  
	 * @param cellEvalu13 the value for pack_data_expand.cell_evalu_13
	 */
	public void setCellEvalu13(Integer cellEvalu13) {
		this.cellEvalu13 = cellEvalu13;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_14  
	 * @return the value of pack_data_expand.cell_evalu_14
	 */
	public Integer getCellEvalu14() {
		return cellEvalu14;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_14  
	 * @param cellEvalu14 the value for pack_data_expand.cell_evalu_14
	 */
	public void setCellEvalu14(Integer cellEvalu14) {
		this.cellEvalu14 = cellEvalu14;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_15  
	 * @return the value of pack_data_expand.cell_evalu_15
	 */
	public Integer getCellEvalu15() {
		return cellEvalu15;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_15  
	 * @param cellEvalu15 the value for pack_data_expand.cell_evalu_15
	 */
	public void setCellEvalu15(Integer cellEvalu15) {
		this.cellEvalu15 = cellEvalu15;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_16  
	 * @return the value of pack_data_expand.cell_evalu_16
	 */
	public Integer getCellEvalu16() {
		return cellEvalu16;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_16  
	 * @param cellEvalu16 the value for pack_data_expand.cell_evalu_16
	 */
	public void setCellEvalu16(Integer cellEvalu16) {
		this.cellEvalu16 = cellEvalu16;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_17  
	 * @return the value of pack_data_expand.cell_evalu_17
	 */
	public Integer getCellEvalu17() {
		return cellEvalu17;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_17  
	 * @param cellEvalu17 the value for pack_data_expand.cell_evalu_17
	 */
	public void setCellEvalu17(Integer cellEvalu17) {
		this.cellEvalu17 = cellEvalu17;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_18  
	 * @return the value of pack_data_expand.cell_evalu_18
	 */
	public Integer getCellEvalu18() {
		return cellEvalu18;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_18  
	 * @param cellEvalu18 the value for pack_data_expand.cell_evalu_18
	 */
	public void setCellEvalu18(Integer cellEvalu18) {
		this.cellEvalu18 = cellEvalu18;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_19  
	 * @return the value of pack_data_expand.cell_evalu_19
	 */
	public Integer getCellEvalu19() {
		return cellEvalu19;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_19  
	 * @param cellEvalu19 the value for pack_data_expand.cell_evalu_19
	 */
	public void setCellEvalu19(Integer cellEvalu19) {
		this.cellEvalu19 = cellEvalu19;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_20  
	 * @return the value of pack_data_expand.cell_evalu_20
	 */
	public Integer getCellEvalu20() {
		return cellEvalu20;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_20  
	 * @param cellEvalu20 the value for pack_data_expand.cell_evalu_20
	 */
	public void setCellEvalu20(Integer cellEvalu20) {
		this.cellEvalu20 = cellEvalu20;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_21  
	 * @return the value of pack_data_expand.cell_evalu_21
	 */
	public Integer getCellEvalu21() {
		return cellEvalu21;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_21  
	 * @param cellEvalu21 the value for pack_data_expand.cell_evalu_21
	 */
	public void setCellEvalu21(Integer cellEvalu21) {
		this.cellEvalu21 = cellEvalu21;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_22  
	 * @return the value of pack_data_expand.cell_evalu_22
	 */
	public Integer getCellEvalu22() {
		return cellEvalu22;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_22  
	 * @param cellEvalu22 the value for pack_data_expand.cell_evalu_22
	 */
	public void setCellEvalu22(Integer cellEvalu22) {
		this.cellEvalu22 = cellEvalu22;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_23  
	 * @return the value of pack_data_expand.cell_evalu_23
	 */
	public Integer getCellEvalu23() {
		return cellEvalu23;
	}

	/**
	 * This method sets the value of the database column pack_data_expand.cell_evalu_23  
	 * @param cellEvalu23 the value for pack_data_expand.cell_evalu_23
	 */
	public void setCellEvalu23(Integer cellEvalu23) {
		this.cellEvalu23 = cellEvalu23;
	}

	/**
	 * This method returns the value of the database column pack_data_expand.cell_evalu_24  
	 * @return the value of pack_data_expand.cell_evalu_24
	 */
	public Integer getCellEvalu24() {
		return cellEvalu24;
	}

    /**
     * This method sets the value of the database column pack_data_expand.cell_evalu_24
     * @param cellEvalu24 the value for pack_data_expand.cell_evalu_24
     */
    public void setCellEvalu24(Integer cellEvalu24) {
        this.cellEvalu24 = cellEvalu24;
    }

    public Integer getCellCapSort1() {
        return cellCapSort1;
    }

    public void setCellCapSort1(Integer cellCapSort1) {
        this.cellCapSort1 = cellCapSort1;
    }

    public Integer getCellCapSort2() {
        return cellCapSort2;
    }

    public void setCellCapSort2(Integer cellCapSort2) {
        this.cellCapSort2 = cellCapSort2;
    }

    public Integer getCellCapSort3() {
        return cellCapSort3;
    }

    public void setCellCapSort3(Integer cellCapSort3) {
        this.cellCapSort3 = cellCapSort3;
    }

    public Integer getCellCapSort4() {
        return cellCapSort4;
    }

    public void setCellCapSort4(Integer cellCapSort4) {
        this.cellCapSort4 = cellCapSort4;
    }

    public Integer getCellCapSort5() {
        return cellCapSort5;
    }

    public void setCellCapSort5(Integer cellCapSort5) {
        this.cellCapSort5 = cellCapSort5;
    }

    public Integer getCellCapSort6() {
        return cellCapSort6;
    }

    public void setCellCapSort6(Integer cellCapSort6) {
        this.cellCapSort6 = cellCapSort6;
    }

    public Integer getCellCapSort7() {
        return cellCapSort7;
    }

    public void setCellCapSort7(Integer cellCapSort7) {
        this.cellCapSort7 = cellCapSort7;
    }

    public Integer getCellCapSort8() {
        return cellCapSort8;
    }

    public void setCellCapSort8(Integer cellCapSort8) {
        this.cellCapSort8 = cellCapSort8;
    }

    public Integer getCellCapSort9() {
        return cellCapSort9;
    }

    public void setCellCapSort9(Integer cellCapSort9) {
        this.cellCapSort9 = cellCapSort9;
    }

    public Integer getCellCapSort10() {
        return cellCapSort10;
    }

    public void setCellCapSort10(Integer cellCapSort10) {
        this.cellCapSort10 = cellCapSort10;
    }

    public Integer getCellCapSort11() {
        return cellCapSort11;
    }

    public void setCellCapSort11(Integer cellCapSort11) {
        this.cellCapSort11 = cellCapSort11;
    }

    public Integer getCellCapSort12() {
        return cellCapSort12;
    }

    public void setCellCapSort12(Integer cellCapSort12) {
        this.cellCapSort12 = cellCapSort12;
    }

    public Integer getCellCapSort13() {
        return cellCapSort13;
    }

    public void setCellCapSort13(Integer cellCapSort13) {
        this.cellCapSort13 = cellCapSort13;
    }

    public Integer getCellCapSort14() {
        return cellCapSort14;
    }

    public void setCellCapSort14(Integer cellCapSort14) {
        this.cellCapSort14 = cellCapSort14;
    }

    public Integer getCellCapSort15() {
        return cellCapSort15;
    }

    public void setCellCapSort15(Integer cellCapSort15) {
        this.cellCapSort15 = cellCapSort15;
    }

    public Integer getCellCapSort16() {
        return cellCapSort16;
    }

    public void setCellCapSort16(Integer cellCapSort16) {
        this.cellCapSort16 = cellCapSort16;
    }

    public Integer getCellCapSort17() {
        return cellCapSort17;
    }

    public void setCellCapSort17(Integer cellCapSort17) {
        this.cellCapSort17 = cellCapSort17;
    }

    public Integer getCellCapSort18() {
        return cellCapSort18;
    }

    public void setCellCapSort18(Integer cellCapSort18) {
        this.cellCapSort18 = cellCapSort18;
    }

    public Integer getCellCapSort19() {
        return cellCapSort19;
    }

    public void setCellCapSort19(Integer cellCapSort19) {
        this.cellCapSort19 = cellCapSort19;
    }

    public Integer getCellCapSort20() {
        return cellCapSort20;
    }

    public void setCellCapSort20(Integer cellCapSort20) {
        this.cellCapSort20 = cellCapSort20;
    }

    public Integer getCellCapSort21() {
        return cellCapSort21;
    }

    public void setCellCapSort21(Integer cellCapSort21) {
        this.cellCapSort21 = cellCapSort21;
    }

    public Integer getCellCapSort22() {
        return cellCapSort22;
    }

    public void setCellCapSort22(Integer cellCapSort22) {
        this.cellCapSort22 = cellCapSort22;
    }

    public Integer getCellCapSort23() {
        return cellCapSort23;
    }

    public void setCellCapSort23(Integer cellCapSort23) {
        this.cellCapSort23 = cellCapSort23;
    }

    public Integer getCellCapSort24() {
        return cellCapSort24;
    }

    public void setCellCapSort24(Integer cellCapSort24) {
        this.cellCapSort24 = cellCapSort24;
    }
}