package com.station.moudles.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table pack_data_info  
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value = "PackDataInfo", description = "PackDataInfo描述")
public class PackDataInfo {
	/**
	 * This field corresponds to the database column pack_data_info.id  
	 */
	@ApiModelProperty(value = "pk", required = true)
	private Integer id;

	/**
	 * This field corresponds to the database column pack_data_info.gprs_id  基站gprs ID
	 */
	@ApiModelProperty(value = "基站gprs ID", example = "基站gprs ID", required = false)
	private String gprsId;

	/**
	 * This field corresponds to the database column pack_data_info.rcv_time  数据接收时间
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@ApiModelProperty(value = "数据接收时间")
	private Date rcvTime;

	/**
	 * This field corresponds to the database column pack_data_info.state  电池状态： 充电,放电,浮充
	 */
	@ApiModelProperty(value = "电池状态： 充电,放电,浮充", example = "电池状态： 充电,放电,浮充", required = false)
	private String state;

	/**
	 * This field corresponds to the database column pack_data_info.gen_vol  总电压 0~999.999 
	 */
	@ApiModelProperty(value = "总电压 0~999.999 ", required = false)
	private BigDecimal genVol;

	/**
	 * This field corresponds to the database column pack_data_info.gen_cur  总电流 -999.999~999.999 负数为充电电流，负数数为放电电流
	 */
	@ApiModelProperty(value = "总电流 -999.999~999.999 负数为充电电流，负数数为放电电流", required = false)
	private BigDecimal genCur;

	/**
	 * This field corresponds to the database column pack_data_info.environ_tem  环境温度
	 */
	@ApiModelProperty(value = "环境温度", required = false)
	private Integer environTem;

	/**
	 * This field corresponds to the database column pack_data_info.soc  基站电池容量百分比， 范围 0~100
	 */
	@ApiModelProperty(value = "基站电池容量百分比， 范围 0~100", required = false)
	private Short soc;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_1  1号电池单体电压 
	 */
	@ApiModelProperty(value = "1号电池单体电压 ", required = false)
	private BigDecimal cellVol1;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_2  
	 */
	@ApiModelProperty(value = "cellVol2", required = false)
	private BigDecimal cellVol2;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_3  
	 */
	@ApiModelProperty(value = "cellVol3", required = false)
	private BigDecimal cellVol3;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_4  
	 */
	@ApiModelProperty(value = "cellVol4", required = false)
	private BigDecimal cellVol4;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_5  
	 */
	@ApiModelProperty(value = "cellVol5", required = false)
	private BigDecimal cellVol5;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_6  
	 */
	@ApiModelProperty(value = "cellVol6", required = false)
	private BigDecimal cellVol6;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_7  
	 */
	@ApiModelProperty(value = "cellVol7", required = false)
	private BigDecimal cellVol7;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_8  
	 */
	@ApiModelProperty(value = "cellVol8", required = false)
	private BigDecimal cellVol8;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_9  
	 */
	@ApiModelProperty(value = "cellVol9", required = false)
	private BigDecimal cellVol9;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_10  
	 */
	@ApiModelProperty(value = "cellVol10", required = false)
	private BigDecimal cellVol10;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_11  
	 */
	@ApiModelProperty(value = "cellVol11", required = false)
	private BigDecimal cellVol11;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_12  
	 */
	@ApiModelProperty(value = "cellVol12", required = false)
	private BigDecimal cellVol12;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_13  
	 */
	@ApiModelProperty(value = "cellVol13", required = false)
	private BigDecimal cellVol13;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_14  
	 */
	@ApiModelProperty(value = "cellVol14", required = false)
	private BigDecimal cellVol14;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_15  
	 */
	@ApiModelProperty(value = "cellVol15", required = false)
	private BigDecimal cellVol15;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_16  
	 */
	@ApiModelProperty(value = "cellVol16", required = false)
	private BigDecimal cellVol16;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_17  
	 */
	@ApiModelProperty(value = "cellVol17", required = false)
	private BigDecimal cellVol17;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_18  
	 */
	@ApiModelProperty(value = "cellVol18", required = false)
	private BigDecimal cellVol18;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_19  
	 */
	@ApiModelProperty(value = "cellVol19", required = false)
	private BigDecimal cellVol19;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_20  
	 */
	@ApiModelProperty(value = "cellVol20", required = false)
	private BigDecimal cellVol20;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_21  
	 */
	@ApiModelProperty(value = "cellVol21", required = false)
	private BigDecimal cellVol21;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_22  
	 */
	@ApiModelProperty(value = "cellVol22", required = false)
	private BigDecimal cellVol22;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_23  
	 */
	@ApiModelProperty(value = "cellVol23", required = false)
	private BigDecimal cellVol23;

	/**
	 * This field corresponds to the database column pack_data_info.cell_vol_24  
	 */
	@ApiModelProperty(value = "cellVol24", required = false)
	private BigDecimal cellVol24;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_1  1号电池温度 -45~120
	 */
	@ApiModelProperty(value = "1号电池温度 -45~120", required = false)
	private Integer cellTem1;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_2  
	 */
	@ApiModelProperty(value = "cellTem2", required = false)
	private Integer cellTem2;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_3  
	 */
	@ApiModelProperty(value = "cellTem3", required = false)
	private Integer cellTem3;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_4  
	 */
	@ApiModelProperty(value = "cellTem4", required = false)
	private Integer cellTem4;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_5  
	 */
	@ApiModelProperty(value = "cellTem5", required = false)
	private Integer cellTem5;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_6  
	 */
	@ApiModelProperty(value = "cellTem6", required = false)
	private Integer cellTem6;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_7  
	 */
	@ApiModelProperty(value = "cellTem7", required = false)
	private Integer cellTem7;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_8  
	 */
	@ApiModelProperty(value = "cellTem8", required = false)
	private Integer cellTem8;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_9  
	 */
	@ApiModelProperty(value = "cellTem9", required = false)
	private Integer cellTem9;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_10  
	 */
	@ApiModelProperty(value = "cellTem10", required = false)
	private Integer cellTem10;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_11  
	 */
	@ApiModelProperty(value = "cellTem11", required = false)
	private Integer cellTem11;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_12  
	 */
	@ApiModelProperty(value = "cellTem12", required = false)
	private Integer cellTem12;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_13  
	 */
	@ApiModelProperty(value = "cellTem13", required = false)
	private Integer cellTem13;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_14  
	 */
	@ApiModelProperty(value = "cellTem14", required = false)
	private Integer cellTem14;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_15  
	 */
	@ApiModelProperty(value = "cellTem15", required = false)
	private Integer cellTem15;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_16  
	 */
	@ApiModelProperty(value = "cellTem16", required = false)
	private Integer cellTem16;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_17  
	 */
	@ApiModelProperty(value = "cellTem17", required = false)
	private Integer cellTem17;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_18  
	 */
	@ApiModelProperty(value = "cellTem18", required = false)
	private Integer cellTem18;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_19  
	 */
	@ApiModelProperty(value = "cellTem19", required = false)
	private Integer cellTem19;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_20  
	 */
	@ApiModelProperty(value = "cellTem20", required = false)
	private Integer cellTem20;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_21  
	 */
	@ApiModelProperty(value = "cellTem21", required = false)
	private Integer cellTem21;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_22  
	 */
	@ApiModelProperty(value = "cellTem22", required = false)
	private Integer cellTem22;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_23  
	 */
	@ApiModelProperty(value = "cellTem23", required = false)
	private Integer cellTem23;

	/**
	 * This field corresponds to the database column pack_data_info.cell_tem_24  
	 */
	@ApiModelProperty(value = "cellTem24", required = false)
	private Integer cellTem24;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_1  1号电池的均衡状态 bool type，1均衡中
	 */
	@ApiModelProperty(value = "1号电池的均衡状态 bool type，1均衡中", required = false)
	private Byte cellEqu1;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_2  
	 */
	@ApiModelProperty(value = "cellEqu2", required = false)
	private Byte cellEqu2;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_3  
	 */
	@ApiModelProperty(value = "cellEqu3", required = false)
	private Byte cellEqu3;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_4  
	 */
	@ApiModelProperty(value = "cellEqu4", required = false)
	private Byte cellEqu4;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_5  
	 */
	@ApiModelProperty(value = "cellEqu5", required = false)
	private Byte cellEqu5;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_6  
	 */
	@ApiModelProperty(value = "cellEqu6", required = false)
	private Byte cellEqu6;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_7  
	 */
	@ApiModelProperty(value = "cellEqu7", required = false)
	private Byte cellEqu7;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_8  
	 */
	@ApiModelProperty(value = "cellEqu8", required = false)
	private Byte cellEqu8;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_9  
	 */
	@ApiModelProperty(value = "cellEqu9", required = false)
	private Byte cellEqu9;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_10  
	 */
	@ApiModelProperty(value = "cellEqu10", required = false)
	private Byte cellEqu10;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_11  
	 */
	@ApiModelProperty(value = "cellEqu11", required = false)
	private Byte cellEqu11;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_12  
	 */
	@ApiModelProperty(value = "cellEqu12", required = false)
	private Byte cellEqu12;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_13  
	 */
	@ApiModelProperty(value = "cellEqu13", required = false)
	private Byte cellEqu13;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_14  
	 */
	@ApiModelProperty(value = "cellEqu14", required = false)
	private Byte cellEqu14;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_15  
	 */
	@ApiModelProperty(value = "cellEqu15", required = false)
	private Byte cellEqu15;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_16  
	 */
	@ApiModelProperty(value = "cellEqu16", required = false)
	private Byte cellEqu16;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_17  
	 */
	@ApiModelProperty(value = "cellEqu17", required = false)
	private Byte cellEqu17;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_18  
	 */
	@ApiModelProperty(value = "cellEqu18", required = false)
	private Byte cellEqu18;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_19  
	 */
	@ApiModelProperty(value = "cellEqu19", required = false)
	private Byte cellEqu19;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_20  
	 */
	@ApiModelProperty(value = "cellEqu20", required = false)
	private Byte cellEqu20;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_21  
	 */
	@ApiModelProperty(value = "cellEqu21", required = false)
	private Byte cellEqu21;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_22  
	 */
	@ApiModelProperty(value = "cellEqu22", required = false)
	private Byte cellEqu22;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_23  
	 */
	@ApiModelProperty(value = "cellEqu23", required = false)
	private Byte cellEqu23;

	/**
	 * This field corresponds to the database column pack_data_info.cell_equ_24  
	 */
	@ApiModelProperty(value = "cellEqu24", required = false)
	private Byte cellEqu24;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_1  
	 */
	@ApiModelProperty(value = "comSuc1", required = false)
	private Integer comSuc1;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_2  
	 */
	@ApiModelProperty(value = "comSuc2", required = false)
	private Integer comSuc2;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_3  
	 */
	@ApiModelProperty(value = "comSuc3", required = false)
	private Integer comSuc3;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_4  
	 */
	@ApiModelProperty(value = "comSuc4", required = false)
	private Integer comSuc4;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_5  
	 */
	@ApiModelProperty(value = "comSuc5", required = false)
	private Integer comSuc5;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_6  
	 */
	@ApiModelProperty(value = "comSuc6", required = false)
	private Integer comSuc6;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_7  
	 */
	@ApiModelProperty(value = "comSuc7", required = false)
	private Integer comSuc7;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_8  
	 */
	@ApiModelProperty(value = "comSuc8", required = false)
	private Integer comSuc8;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_9  
	 */
	@ApiModelProperty(value = "comSuc9", required = false)
	private Integer comSuc9;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_10  
	 */
	@ApiModelProperty(value = "comSuc10", required = false)
	private Integer comSuc10;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_11  
	 */
	@ApiModelProperty(value = "comSuc11", required = false)
	private Integer comSuc11;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_12  
	 */
	@ApiModelProperty(value = "comSuc12", required = false)
	private Integer comSuc12;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_13  
	 */
	@ApiModelProperty(value = "comSuc13", required = false)
	private Integer comSuc13;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_14  
	 */
	@ApiModelProperty(value = "comSuc14", required = false)
	private Integer comSuc14;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_15  
	 */
	@ApiModelProperty(value = "comSuc15", required = false)
	private Integer comSuc15;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_16  
	 */
	@ApiModelProperty(value = "comSuc16", required = false)
	private Integer comSuc16;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_17  
	 */
	@ApiModelProperty(value = "comSuc17", required = false)
	private Integer comSuc17;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_18  
	 */
	@ApiModelProperty(value = "comSuc18", required = false)
	private Integer comSuc18;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_19  
	 */
	@ApiModelProperty(value = "comSuc19", required = false)
	private Integer comSuc19;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_20  
	 */
	@ApiModelProperty(value = "comSuc20", required = false)
	private Integer comSuc20;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_21  
	 */
	@ApiModelProperty(value = "comSuc21", required = false)
	private Integer comSuc21;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_22  
	 */
	@ApiModelProperty(value = "comSuc22", required = false)
	private Integer comSuc22;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_23  
	 */
	@ApiModelProperty(value = "comSuc23", required = false)
	private Integer comSuc23;

	/**
	 * This field corresponds to the database column pack_data_info.com_suc_24  
	 */
	@ApiModelProperty(value = "comSuc24", required = false)
	private Integer comSuc24;

	/**
	 * This field corresponds to the database column pack_data_info.passive_balance  是否支持被动均衡，1支持，0支持
	 */
	@ApiModelProperty(value = "是否支持被动均衡，1支持，0支持", required = false)
	private Byte passiveBalance;

	/**
	 * This field corresponds to the database column pack_data_info.initiative_balance  是否支持主动均衡，1支持，0支持,1就是复用设备，其他诊断设备
	 */
	@ApiModelProperty(value = "是否支持主动均衡，1支持，0支持,1就是复用设备，其他诊断设备", required = false)
	private Byte initiativeBalance;

	/**
	 * This method returns the value of the database column pack_data_info.id  
	 * @return the value of pack_data_info.id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method sets the value of the database column pack_data_info.id  
	 * @param id the value for pack_data_info.id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method returns the value of the database column pack_data_info.gprs_id  基站gprs ID
	
	 * @return the value of pack_data_info.gprs_id
	 */
	public String getGprsId() {
		return gprsId;
	}

	/**
	 * This method sets the value of the database column pack_data_info.gprs_id  基站gprs ID
	
	 * @param gprsId the value for pack_data_info.gprs_id
	 */
	public void setGprsId(String gprsId) {
		this.gprsId = gprsId == null ? null : gprsId.trim();
	}

	/**
	 * This method returns the value of the database column pack_data_info.rcv_time  数据接收时间
	 * @return the value of pack_data_info.rcv_time
	 */
	public Date getRcvTime() {
		return rcvTime;
	}

	/**
	 * This method sets the value of the database column pack_data_info.rcv_time  数据接收时间
	 * @param rcvTime the value for pack_data_info.rcv_time
	 */
	public void setRcvTime(Date rcvTime) {
		this.rcvTime = rcvTime;
	}

	/**
	 * This method returns the value of the database column pack_data_info.state  电池状态： 充电,放电,浮充
	 * @return the value of pack_data_info.state
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method sets the value of the database column pack_data_info.state  电池状态： 充电,放电,浮充
	 * @param state the value for pack_data_info.state
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method returns the value of the database column pack_data_info.gen_vol  总电压 0~999.999 
	 * @return the value of pack_data_info.gen_vol
	 */
	public BigDecimal getGenVol() {
		return genVol;
	}

	/**
	 * This method sets the value of the database column pack_data_info.gen_vol  总电压 0~999.999 
	 * @param genVol the value for pack_data_info.gen_vol
	 */
	public void setGenVol(BigDecimal genVol) {
		this.genVol = genVol;
	}

	/**
	 * This method returns the value of the database column pack_data_info.gen_cur  总电流 -999.999~999.999 负数为充电电流，负数数为放电电流
	 * @return the value of pack_data_info.gen_cur
	 */
	public BigDecimal getGenCur() {
		return genCur;
	}

	/**
	 * This method sets the value of the database column pack_data_info.gen_cur  总电流 -999.999~999.999 负数为充电电流，负数数为放电电流
	 * @param genCur the value for pack_data_info.gen_cur
	 */
	public void setGenCur(BigDecimal genCur) {
		this.genCur = genCur;
	}

	/**
	 * This method returns the value of the database column pack_data_info.environ_tem  环境温度
	 * @return the value of pack_data_info.environ_tem
	 */
	public Integer getEnvironTem() {
		return environTem;
	}

	/**
	 * This method sets the value of the database column pack_data_info.environ_tem  环境温度
	 * @param environTem the value for pack_data_info.environ_tem
	 */
	public void setEnvironTem(Integer environTem) {
		this.environTem = environTem;
	}

	/**
	 * This method returns the value of the database column pack_data_info.soc  基站电池容量百分比， 范围 0~100
	 * @return the value of pack_data_info.soc
	 */
	public Short getSoc() {
		return soc;
	}

	/**
	 * This method sets the value of the database column pack_data_info.soc  基站电池容量百分比， 范围 0~100
	 * @param soc the value for pack_data_info.soc
	 */
	public void setSoc(Short soc) {
		this.soc = soc;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_1  1号电池单体电压 
	 * @return the value of pack_data_info.cell_vol_1
	 */
	public BigDecimal getCellVol1() {
		return cellVol1;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_1  1号电池单体电压 
	 * @param cellVol1 the value for pack_data_info.cell_vol_1
	 */
	public void setCellVol1(BigDecimal cellVol1) {
		this.cellVol1 = cellVol1;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_2  
	 * @return the value of pack_data_info.cell_vol_2
	 */
	public BigDecimal getCellVol2() {
		return cellVol2;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_2  
	 * @param cellVol2 the value for pack_data_info.cell_vol_2
	 */
	public void setCellVol2(BigDecimal cellVol2) {
		this.cellVol2 = cellVol2;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_3  
	 * @return the value of pack_data_info.cell_vol_3
	 */
	public BigDecimal getCellVol3() {
		return cellVol3;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_3  
	 * @param cellVol3 the value for pack_data_info.cell_vol_3
	 */
	public void setCellVol3(BigDecimal cellVol3) {
		this.cellVol3 = cellVol3;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_4  
	 * @return the value of pack_data_info.cell_vol_4
	 */
	public BigDecimal getCellVol4() {
		return cellVol4;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_4  
	 * @param cellVol4 the value for pack_data_info.cell_vol_4
	 */
	public void setCellVol4(BigDecimal cellVol4) {
		this.cellVol4 = cellVol4;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_5  
	 * @return the value of pack_data_info.cell_vol_5
	 */
	public BigDecimal getCellVol5() {
		return cellVol5;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_5  
	 * @param cellVol5 the value for pack_data_info.cell_vol_5
	 */
	public void setCellVol5(BigDecimal cellVol5) {
		this.cellVol5 = cellVol5;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_6  
	 * @return the value of pack_data_info.cell_vol_6
	 */
	public BigDecimal getCellVol6() {
		return cellVol6;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_6  
	 * @param cellVol6 the value for pack_data_info.cell_vol_6
	 */
	public void setCellVol6(BigDecimal cellVol6) {
		this.cellVol6 = cellVol6;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_7  
	 * @return the value of pack_data_info.cell_vol_7
	 */
	public BigDecimal getCellVol7() {
		return cellVol7;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_7  
	 * @param cellVol7 the value for pack_data_info.cell_vol_7
	 */
	public void setCellVol7(BigDecimal cellVol7) {
		this.cellVol7 = cellVol7;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_8  
	 * @return the value of pack_data_info.cell_vol_8
	 */
	public BigDecimal getCellVol8() {
		return cellVol8;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_8  
	 * @param cellVol8 the value for pack_data_info.cell_vol_8
	 */
	public void setCellVol8(BigDecimal cellVol8) {
		this.cellVol8 = cellVol8;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_9  
	 * @return the value of pack_data_info.cell_vol_9
	 */
	public BigDecimal getCellVol9() {
		return cellVol9;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_9  
	 * @param cellVol9 the value for pack_data_info.cell_vol_9
	 */
	public void setCellVol9(BigDecimal cellVol9) {
		this.cellVol9 = cellVol9;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_10  
	 * @return the value of pack_data_info.cell_vol_10
	 */
	public BigDecimal getCellVol10() {
		return cellVol10;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_10  
	 * @param cellVol10 the value for pack_data_info.cell_vol_10
	 */
	public void setCellVol10(BigDecimal cellVol10) {
		this.cellVol10 = cellVol10;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_11  
	 * @return the value of pack_data_info.cell_vol_11
	 */
	public BigDecimal getCellVol11() {
		return cellVol11;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_11  
	 * @param cellVol11 the value for pack_data_info.cell_vol_11
	 */
	public void setCellVol11(BigDecimal cellVol11) {
		this.cellVol11 = cellVol11;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_12  
	 * @return the value of pack_data_info.cell_vol_12
	 */
	public BigDecimal getCellVol12() {
		return cellVol12;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_12  
	 * @param cellVol12 the value for pack_data_info.cell_vol_12
	 */
	public void setCellVol12(BigDecimal cellVol12) {
		this.cellVol12 = cellVol12;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_13  
	 * @return the value of pack_data_info.cell_vol_13
	 */
	public BigDecimal getCellVol13() {
		return cellVol13;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_13  
	 * @param cellVol13 the value for pack_data_info.cell_vol_13
	 */
	public void setCellVol13(BigDecimal cellVol13) {
		this.cellVol13 = cellVol13;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_14  
	 * @return the value of pack_data_info.cell_vol_14
	 */
	public BigDecimal getCellVol14() {
		return cellVol14;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_14  
	 * @param cellVol14 the value for pack_data_info.cell_vol_14
	 */
	public void setCellVol14(BigDecimal cellVol14) {
		this.cellVol14 = cellVol14;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_15  
	 * @return the value of pack_data_info.cell_vol_15
	 */
	public BigDecimal getCellVol15() {
		return cellVol15;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_15  
	 * @param cellVol15 the value for pack_data_info.cell_vol_15
	 */
	public void setCellVol15(BigDecimal cellVol15) {
		this.cellVol15 = cellVol15;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_16  
	 * @return the value of pack_data_info.cell_vol_16
	 */
	public BigDecimal getCellVol16() {
		return cellVol16;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_16  
	 * @param cellVol16 the value for pack_data_info.cell_vol_16
	 */
	public void setCellVol16(BigDecimal cellVol16) {
		this.cellVol16 = cellVol16;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_17  
	 * @return the value of pack_data_info.cell_vol_17
	 */
	public BigDecimal getCellVol17() {
		return cellVol17;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_17  
	 * @param cellVol17 the value for pack_data_info.cell_vol_17
	 */
	public void setCellVol17(BigDecimal cellVol17) {
		this.cellVol17 = cellVol17;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_18  
	 * @return the value of pack_data_info.cell_vol_18
	 */
	public BigDecimal getCellVol18() {
		return cellVol18;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_18  
	 * @param cellVol18 the value for pack_data_info.cell_vol_18
	 */
	public void setCellVol18(BigDecimal cellVol18) {
		this.cellVol18 = cellVol18;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_19  
	 * @return the value of pack_data_info.cell_vol_19
	 */
	public BigDecimal getCellVol19() {
		return cellVol19;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_19  
	 * @param cellVol19 the value for pack_data_info.cell_vol_19
	 */
	public void setCellVol19(BigDecimal cellVol19) {
		this.cellVol19 = cellVol19;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_20  
	 * @return the value of pack_data_info.cell_vol_20
	 */
	public BigDecimal getCellVol20() {
		return cellVol20;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_20  
	 * @param cellVol20 the value for pack_data_info.cell_vol_20
	 */
	public void setCellVol20(BigDecimal cellVol20) {
		this.cellVol20 = cellVol20;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_21  
	 * @return the value of pack_data_info.cell_vol_21
	 */
	public BigDecimal getCellVol21() {
		return cellVol21;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_21  
	 * @param cellVol21 the value for pack_data_info.cell_vol_21
	 */
	public void setCellVol21(BigDecimal cellVol21) {
		this.cellVol21 = cellVol21;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_22  
	 * @return the value of pack_data_info.cell_vol_22
	 */
	public BigDecimal getCellVol22() {
		return cellVol22;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_22  
	 * @param cellVol22 the value for pack_data_info.cell_vol_22
	 */
	public void setCellVol22(BigDecimal cellVol22) {
		this.cellVol22 = cellVol22;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_23  
	 * @return the value of pack_data_info.cell_vol_23
	 */
	public BigDecimal getCellVol23() {
		return cellVol23;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_23  
	 * @param cellVol23 the value for pack_data_info.cell_vol_23
	 */
	public void setCellVol23(BigDecimal cellVol23) {
		this.cellVol23 = cellVol23;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_vol_24  
	 * @return the value of pack_data_info.cell_vol_24
	 */
	public BigDecimal getCellVol24() {
		return cellVol24;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_vol_24  
	 * @param cellVol24 the value for pack_data_info.cell_vol_24
	 */
	public void setCellVol24(BigDecimal cellVol24) {
		this.cellVol24 = cellVol24;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_1  1号电池温度 -45~120
	 * @return the value of pack_data_info.cell_tem_1
	 */
	public Integer getCellTem1() {
		return cellTem1;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_1  1号电池温度 -45~120
	 * @param cellTem1 the value for pack_data_info.cell_tem_1
	 */
	public void setCellTem1(Integer cellTem1) {
		this.cellTem1 = cellTem1;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_2  
	 * @return the value of pack_data_info.cell_tem_2
	 */
	public Integer getCellTem2() {
		return cellTem2;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_2  
	 * @param cellTem2 the value for pack_data_info.cell_tem_2
	 */
	public void setCellTem2(Integer cellTem2) {
		this.cellTem2 = cellTem2;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_3  
	 * @return the value of pack_data_info.cell_tem_3
	 */
	public Integer getCellTem3() {
		return cellTem3;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_3  
	 * @param cellTem3 the value for pack_data_info.cell_tem_3
	 */
	public void setCellTem3(Integer cellTem3) {
		this.cellTem3 = cellTem3;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_4  
	 * @return the value of pack_data_info.cell_tem_4
	 */
	public Integer getCellTem4() {
		return cellTem4;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_4  
	 * @param cellTem4 the value for pack_data_info.cell_tem_4
	 */
	public void setCellTem4(Integer cellTem4) {
		this.cellTem4 = cellTem4;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_5  
	 * @return the value of pack_data_info.cell_tem_5
	 */
	public Integer getCellTem5() {
		return cellTem5;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_5  
	 * @param cellTem5 the value for pack_data_info.cell_tem_5
	 */
	public void setCellTem5(Integer cellTem5) {
		this.cellTem5 = cellTem5;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_6  
	 * @return the value of pack_data_info.cell_tem_6
	 */
	public Integer getCellTem6() {
		return cellTem6;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_6  
	 * @param cellTem6 the value for pack_data_info.cell_tem_6
	 */
	public void setCellTem6(Integer cellTem6) {
		this.cellTem6 = cellTem6;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_7  
	 * @return the value of pack_data_info.cell_tem_7
	 */
	public Integer getCellTem7() {
		return cellTem7;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_7  
	 * @param cellTem7 the value for pack_data_info.cell_tem_7
	 */
	public void setCellTem7(Integer cellTem7) {
		this.cellTem7 = cellTem7;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_8  
	 * @return the value of pack_data_info.cell_tem_8
	 */
	public Integer getCellTem8() {
		return cellTem8;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_8  
	 * @param cellTem8 the value for pack_data_info.cell_tem_8
	 */
	public void setCellTem8(Integer cellTem8) {
		this.cellTem8 = cellTem8;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_9  
	 * @return the value of pack_data_info.cell_tem_9
	 */
	public Integer getCellTem9() {
		return cellTem9;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_9  
	 * @param cellTem9 the value for pack_data_info.cell_tem_9
	 */
	public void setCellTem9(Integer cellTem9) {
		this.cellTem9 = cellTem9;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_10  
	 * @return the value of pack_data_info.cell_tem_10
	 */
	public Integer getCellTem10() {
		return cellTem10;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_10  
	 * @param cellTem10 the value for pack_data_info.cell_tem_10
	 */
	public void setCellTem10(Integer cellTem10) {
		this.cellTem10 = cellTem10;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_11  
	 * @return the value of pack_data_info.cell_tem_11
	 */
	public Integer getCellTem11() {
		return cellTem11;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_11  
	 * @param cellTem11 the value for pack_data_info.cell_tem_11
	 */
	public void setCellTem11(Integer cellTem11) {
		this.cellTem11 = cellTem11;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_12  
	 * @return the value of pack_data_info.cell_tem_12
	 */
	public Integer getCellTem12() {
		return cellTem12;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_12  
	 * @param cellTem12 the value for pack_data_info.cell_tem_12
	 */
	public void setCellTem12(Integer cellTem12) {
		this.cellTem12 = cellTem12;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_13  
	 * @return the value of pack_data_info.cell_tem_13
	 */
	public Integer getCellTem13() {
		return cellTem13;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_13  
	 * @param cellTem13 the value for pack_data_info.cell_tem_13
	 */
	public void setCellTem13(Integer cellTem13) {
		this.cellTem13 = cellTem13;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_14  
	 * @return the value of pack_data_info.cell_tem_14
	 */
	public Integer getCellTem14() {
		return cellTem14;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_14  
	 * @param cellTem14 the value for pack_data_info.cell_tem_14
	 */
	public void setCellTem14(Integer cellTem14) {
		this.cellTem14 = cellTem14;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_15  
	 * @return the value of pack_data_info.cell_tem_15
	 */
	public Integer getCellTem15() {
		return cellTem15;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_15  
	 * @param cellTem15 the value for pack_data_info.cell_tem_15
	 */
	public void setCellTem15(Integer cellTem15) {
		this.cellTem15 = cellTem15;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_16  
	 * @return the value of pack_data_info.cell_tem_16
	 */
	public Integer getCellTem16() {
		return cellTem16;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_16  
	 * @param cellTem16 the value for pack_data_info.cell_tem_16
	 */
	public void setCellTem16(Integer cellTem16) {
		this.cellTem16 = cellTem16;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_17  
	 * @return the value of pack_data_info.cell_tem_17
	 */
	public Integer getCellTem17() {
		return cellTem17;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_17  
	 * @param cellTem17 the value for pack_data_info.cell_tem_17
	 */
	public void setCellTem17(Integer cellTem17) {
		this.cellTem17 = cellTem17;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_18  
	 * @return the value of pack_data_info.cell_tem_18
	 */
	public Integer getCellTem18() {
		return cellTem18;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_18  
	 * @param cellTem18 the value for pack_data_info.cell_tem_18
	 */
	public void setCellTem18(Integer cellTem18) {
		this.cellTem18 = cellTem18;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_19  
	 * @return the value of pack_data_info.cell_tem_19
	 */
	public Integer getCellTem19() {
		return cellTem19;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_19  
	 * @param cellTem19 the value for pack_data_info.cell_tem_19
	 */
	public void setCellTem19(Integer cellTem19) {
		this.cellTem19 = cellTem19;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_20  
	 * @return the value of pack_data_info.cell_tem_20
	 */
	public Integer getCellTem20() {
		return cellTem20;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_20  
	 * @param cellTem20 the value for pack_data_info.cell_tem_20
	 */
	public void setCellTem20(Integer cellTem20) {
		this.cellTem20 = cellTem20;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_21  
	 * @return the value of pack_data_info.cell_tem_21
	 */
	public Integer getCellTem21() {
		return cellTem21;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_21  
	 * @param cellTem21 the value for pack_data_info.cell_tem_21
	 */
	public void setCellTem21(Integer cellTem21) {
		this.cellTem21 = cellTem21;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_22  
	 * @return the value of pack_data_info.cell_tem_22
	 */
	public Integer getCellTem22() {
		return cellTem22;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_22  
	 * @param cellTem22 the value for pack_data_info.cell_tem_22
	 */
	public void setCellTem22(Integer cellTem22) {
		this.cellTem22 = cellTem22;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_23  
	 * @return the value of pack_data_info.cell_tem_23
	 */
	public Integer getCellTem23() {
		return cellTem23;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_23  
	 * @param cellTem23 the value for pack_data_info.cell_tem_23
	 */
	public void setCellTem23(Integer cellTem23) {
		this.cellTem23 = cellTem23;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_tem_24  
	 * @return the value of pack_data_info.cell_tem_24
	 */
	public Integer getCellTem24() {
		return cellTem24;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_tem_24  
	 * @param cellTem24 the value for pack_data_info.cell_tem_24
	 */
	public void setCellTem24(Integer cellTem24) {
		this.cellTem24 = cellTem24;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_1  1号电池的均衡状态 bool type，1均衡中
	 * @return the value of pack_data_info.cell_equ_1
	 */
	public Byte getCellEqu1() {
		return cellEqu1;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_1  1号电池的均衡状态 bool type，1均衡中
	 * @param cellEqu1 the value for pack_data_info.cell_equ_1
	 */
	public void setCellEqu1(Byte cellEqu1) {
		this.cellEqu1 = cellEqu1;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_2  
	 * @return the value of pack_data_info.cell_equ_2
	 */
	public Byte getCellEqu2() {
		return cellEqu2;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_2  
	 * @param cellEqu2 the value for pack_data_info.cell_equ_2
	 */
	public void setCellEqu2(Byte cellEqu2) {
		this.cellEqu2 = cellEqu2;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_3  
	 * @return the value of pack_data_info.cell_equ_3
	 */
	public Byte getCellEqu3() {
		return cellEqu3;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_3  
	 * @param cellEqu3 the value for pack_data_info.cell_equ_3
	 */
	public void setCellEqu3(Byte cellEqu3) {
		this.cellEqu3 = cellEqu3;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_4  
	 * @return the value of pack_data_info.cell_equ_4
	 */
	public Byte getCellEqu4() {
		return cellEqu4;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_4  
	 * @param cellEqu4 the value for pack_data_info.cell_equ_4
	 */
	public void setCellEqu4(Byte cellEqu4) {
		this.cellEqu4 = cellEqu4;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_5  
	 * @return the value of pack_data_info.cell_equ_5
	 */
	public Byte getCellEqu5() {
		return cellEqu5;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_5  
	 * @param cellEqu5 the value for pack_data_info.cell_equ_5
	 */
	public void setCellEqu5(Byte cellEqu5) {
		this.cellEqu5 = cellEqu5;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_6  
	 * @return the value of pack_data_info.cell_equ_6
	 */
	public Byte getCellEqu6() {
		return cellEqu6;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_6  
	 * @param cellEqu6 the value for pack_data_info.cell_equ_6
	 */
	public void setCellEqu6(Byte cellEqu6) {
		this.cellEqu6 = cellEqu6;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_7  
	 * @return the value of pack_data_info.cell_equ_7
	 */
	public Byte getCellEqu7() {
		return cellEqu7;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_7  
	 * @param cellEqu7 the value for pack_data_info.cell_equ_7
	 */
	public void setCellEqu7(Byte cellEqu7) {
		this.cellEqu7 = cellEqu7;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_8  
	 * @return the value of pack_data_info.cell_equ_8
	 */
	public Byte getCellEqu8() {
		return cellEqu8;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_8  
	 * @param cellEqu8 the value for pack_data_info.cell_equ_8
	 */
	public void setCellEqu8(Byte cellEqu8) {
		this.cellEqu8 = cellEqu8;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_9  
	 * @return the value of pack_data_info.cell_equ_9
	 */
	public Byte getCellEqu9() {
		return cellEqu9;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_9  
	 * @param cellEqu9 the value for pack_data_info.cell_equ_9
	 */
	public void setCellEqu9(Byte cellEqu9) {
		this.cellEqu9 = cellEqu9;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_10  
	 * @return the value of pack_data_info.cell_equ_10
	 */
	public Byte getCellEqu10() {
		return cellEqu10;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_10  
	 * @param cellEqu10 the value for pack_data_info.cell_equ_10
	 */
	public void setCellEqu10(Byte cellEqu10) {
		this.cellEqu10 = cellEqu10;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_11  
	 * @return the value of pack_data_info.cell_equ_11
	 */
	public Byte getCellEqu11() {
		return cellEqu11;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_11  
	 * @param cellEqu11 the value for pack_data_info.cell_equ_11
	 */
	public void setCellEqu11(Byte cellEqu11) {
		this.cellEqu11 = cellEqu11;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_12  
	 * @return the value of pack_data_info.cell_equ_12
	 */
	public Byte getCellEqu12() {
		return cellEqu12;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_12  
	 * @param cellEqu12 the value for pack_data_info.cell_equ_12
	 */
	public void setCellEqu12(Byte cellEqu12) {
		this.cellEqu12 = cellEqu12;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_13  
	 * @return the value of pack_data_info.cell_equ_13
	 */
	public Byte getCellEqu13() {
		return cellEqu13;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_13  
	 * @param cellEqu13 the value for pack_data_info.cell_equ_13
	 */
	public void setCellEqu13(Byte cellEqu13) {
		this.cellEqu13 = cellEqu13;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_14  
	 * @return the value of pack_data_info.cell_equ_14
	 */
	public Byte getCellEqu14() {
		return cellEqu14;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_14  
	 * @param cellEqu14 the value for pack_data_info.cell_equ_14
	 */
	public void setCellEqu14(Byte cellEqu14) {
		this.cellEqu14 = cellEqu14;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_15  
	 * @return the value of pack_data_info.cell_equ_15
	 */
	public Byte getCellEqu15() {
		return cellEqu15;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_15  
	 * @param cellEqu15 the value for pack_data_info.cell_equ_15
	 */
	public void setCellEqu15(Byte cellEqu15) {
		this.cellEqu15 = cellEqu15;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_16  
	 * @return the value of pack_data_info.cell_equ_16
	 */
	public Byte getCellEqu16() {
		return cellEqu16;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_16  
	 * @param cellEqu16 the value for pack_data_info.cell_equ_16
	 */
	public void setCellEqu16(Byte cellEqu16) {
		this.cellEqu16 = cellEqu16;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_17  
	 * @return the value of pack_data_info.cell_equ_17
	 */
	public Byte getCellEqu17() {
		return cellEqu17;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_17  
	 * @param cellEqu17 the value for pack_data_info.cell_equ_17
	 */
	public void setCellEqu17(Byte cellEqu17) {
		this.cellEqu17 = cellEqu17;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_18  
	 * @return the value of pack_data_info.cell_equ_18
	 */
	public Byte getCellEqu18() {
		return cellEqu18;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_18  
	 * @param cellEqu18 the value for pack_data_info.cell_equ_18
	 */
	public void setCellEqu18(Byte cellEqu18) {
		this.cellEqu18 = cellEqu18;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_19  
	 * @return the value of pack_data_info.cell_equ_19
	 */
	public Byte getCellEqu19() {
		return cellEqu19;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_19  
	 * @param cellEqu19 the value for pack_data_info.cell_equ_19
	 */
	public void setCellEqu19(Byte cellEqu19) {
		this.cellEqu19 = cellEqu19;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_20  
	 * @return the value of pack_data_info.cell_equ_20
	 */
	public Byte getCellEqu20() {
		return cellEqu20;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_20  
	 * @param cellEqu20 the value for pack_data_info.cell_equ_20
	 */
	public void setCellEqu20(Byte cellEqu20) {
		this.cellEqu20 = cellEqu20;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_21  
	 * @return the value of pack_data_info.cell_equ_21
	 */
	public Byte getCellEqu21() {
		return cellEqu21;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_21  
	 * @param cellEqu21 the value for pack_data_info.cell_equ_21
	 */
	public void setCellEqu21(Byte cellEqu21) {
		this.cellEqu21 = cellEqu21;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_22  
	 * @return the value of pack_data_info.cell_equ_22
	 */
	public Byte getCellEqu22() {
		return cellEqu22;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_22  
	 * @param cellEqu22 the value for pack_data_info.cell_equ_22
	 */
	public void setCellEqu22(Byte cellEqu22) {
		this.cellEqu22 = cellEqu22;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_23  
	 * @return the value of pack_data_info.cell_equ_23
	 */
	public Byte getCellEqu23() {
		return cellEqu23;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_23  
	 * @param cellEqu23 the value for pack_data_info.cell_equ_23
	 */
	public void setCellEqu23(Byte cellEqu23) {
		this.cellEqu23 = cellEqu23;
	}

	/**
	 * This method returns the value of the database column pack_data_info.cell_equ_24  
	 * @return the value of pack_data_info.cell_equ_24
	 */
	public Byte getCellEqu24() {
		return cellEqu24;
	}

	/**
	 * This method sets the value of the database column pack_data_info.cell_equ_24  
	 * @param cellEqu24 the value for pack_data_info.cell_equ_24
	 */
	public void setCellEqu24(Byte cellEqu24) {
		this.cellEqu24 = cellEqu24;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_1  
	 * @return the value of pack_data_info.com_suc_1
	 */
	public Integer getComSuc1() {
		return comSuc1;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_1  
	 * @param comSuc1 the value for pack_data_info.com_suc_1
	 */
	public void setComSuc1(Integer comSuc1) {
		this.comSuc1 = comSuc1;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_2  
	 * @return the value of pack_data_info.com_suc_2
	 */
	public Integer getComSuc2() {
		return comSuc2;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_2  
	 * @param comSuc2 the value for pack_data_info.com_suc_2
	 */
	public void setComSuc2(Integer comSuc2) {
		this.comSuc2 = comSuc2;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_3  
	 * @return the value of pack_data_info.com_suc_3
	 */
	public Integer getComSuc3() {
		return comSuc3;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_3  
	 * @param comSuc3 the value for pack_data_info.com_suc_3
	 */
	public void setComSuc3(Integer comSuc3) {
		this.comSuc3 = comSuc3;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_4  
	 * @return the value of pack_data_info.com_suc_4
	 */
	public Integer getComSuc4() {
		return comSuc4;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_4  
	 * @param comSuc4 the value for pack_data_info.com_suc_4
	 */
	public void setComSuc4(Integer comSuc4) {
		this.comSuc4 = comSuc4;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_5  
	 * @return the value of pack_data_info.com_suc_5
	 */
	public Integer getComSuc5() {
		return comSuc5;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_5  
	 * @param comSuc5 the value for pack_data_info.com_suc_5
	 */
	public void setComSuc5(Integer comSuc5) {
		this.comSuc5 = comSuc5;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_6  
	 * @return the value of pack_data_info.com_suc_6
	 */
	public Integer getComSuc6() {
		return comSuc6;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_6  
	 * @param comSuc6 the value for pack_data_info.com_suc_6
	 */
	public void setComSuc6(Integer comSuc6) {
		this.comSuc6 = comSuc6;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_7  
	 * @return the value of pack_data_info.com_suc_7
	 */
	public Integer getComSuc7() {
		return comSuc7;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_7  
	 * @param comSuc7 the value for pack_data_info.com_suc_7
	 */
	public void setComSuc7(Integer comSuc7) {
		this.comSuc7 = comSuc7;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_8  
	 * @return the value of pack_data_info.com_suc_8
	 */
	public Integer getComSuc8() {
		return comSuc8;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_8  
	 * @param comSuc8 the value for pack_data_info.com_suc_8
	 */
	public void setComSuc8(Integer comSuc8) {
		this.comSuc8 = comSuc8;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_9  
	 * @return the value of pack_data_info.com_suc_9
	 */
	public Integer getComSuc9() {
		return comSuc9;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_9  
	 * @param comSuc9 the value for pack_data_info.com_suc_9
	 */
	public void setComSuc9(Integer comSuc9) {
		this.comSuc9 = comSuc9;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_10  
	 * @return the value of pack_data_info.com_suc_10
	 */
	public Integer getComSuc10() {
		return comSuc10;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_10  
	 * @param comSuc10 the value for pack_data_info.com_suc_10
	 */
	public void setComSuc10(Integer comSuc10) {
		this.comSuc10 = comSuc10;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_11  
	 * @return the value of pack_data_info.com_suc_11
	 */
	public Integer getComSuc11() {
		return comSuc11;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_11  
	 * @param comSuc11 the value for pack_data_info.com_suc_11
	 */
	public void setComSuc11(Integer comSuc11) {
		this.comSuc11 = comSuc11;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_12  
	 * @return the value of pack_data_info.com_suc_12
	 */
	public Integer getComSuc12() {
		return comSuc12;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_12  
	 * @param comSuc12 the value for pack_data_info.com_suc_12
	 */
	public void setComSuc12(Integer comSuc12) {
		this.comSuc12 = comSuc12;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_13  
	 * @return the value of pack_data_info.com_suc_13
	 */
	public Integer getComSuc13() {
		return comSuc13;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_13  
	 * @param comSuc13 the value for pack_data_info.com_suc_13
	 */
	public void setComSuc13(Integer comSuc13) {
		this.comSuc13 = comSuc13;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_14  
	 * @return the value of pack_data_info.com_suc_14
	 */
	public Integer getComSuc14() {
		return comSuc14;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_14  
	 * @param comSuc14 the value for pack_data_info.com_suc_14
	 */
	public void setComSuc14(Integer comSuc14) {
		this.comSuc14 = comSuc14;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_15  
	 * @return the value of pack_data_info.com_suc_15
	 */
	public Integer getComSuc15() {
		return comSuc15;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_15  
	 * @param comSuc15 the value for pack_data_info.com_suc_15
	 */
	public void setComSuc15(Integer comSuc15) {
		this.comSuc15 = comSuc15;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_16  
	 * @return the value of pack_data_info.com_suc_16
	 */
	public Integer getComSuc16() {
		return comSuc16;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_16  
	 * @param comSuc16 the value for pack_data_info.com_suc_16
	 */
	public void setComSuc16(Integer comSuc16) {
		this.comSuc16 = comSuc16;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_17  
	 * @return the value of pack_data_info.com_suc_17
	 */
	public Integer getComSuc17() {
		return comSuc17;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_17  
	 * @param comSuc17 the value for pack_data_info.com_suc_17
	 */
	public void setComSuc17(Integer comSuc17) {
		this.comSuc17 = comSuc17;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_18  
	 * @return the value of pack_data_info.com_suc_18
	 */
	public Integer getComSuc18() {
		return comSuc18;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_18  
	 * @param comSuc18 the value for pack_data_info.com_suc_18
	 */
	public void setComSuc18(Integer comSuc18) {
		this.comSuc18 = comSuc18;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_19  
	 * @return the value of pack_data_info.com_suc_19
	 */
	public Integer getComSuc19() {
		return comSuc19;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_19  
	 * @param comSuc19 the value for pack_data_info.com_suc_19
	 */
	public void setComSuc19(Integer comSuc19) {
		this.comSuc19 = comSuc19;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_20  
	 * @return the value of pack_data_info.com_suc_20
	 */
	public Integer getComSuc20() {
		return comSuc20;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_20  
	 * @param comSuc20 the value for pack_data_info.com_suc_20
	 */
	public void setComSuc20(Integer comSuc20) {
		this.comSuc20 = comSuc20;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_21  
	 * @return the value of pack_data_info.com_suc_21
	 */
	public Integer getComSuc21() {
		return comSuc21;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_21  
	 * @param comSuc21 the value for pack_data_info.com_suc_21
	 */
	public void setComSuc21(Integer comSuc21) {
		this.comSuc21 = comSuc21;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_22  
	 * @return the value of pack_data_info.com_suc_22
	 */
	public Integer getComSuc22() {
		return comSuc22;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_22  
	 * @param comSuc22 the value for pack_data_info.com_suc_22
	 */
	public void setComSuc22(Integer comSuc22) {
		this.comSuc22 = comSuc22;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_23  
	 * @return the value of pack_data_info.com_suc_23
	 */
	public Integer getComSuc23() {
		return comSuc23;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_23  
	 * @param comSuc23 the value for pack_data_info.com_suc_23
	 */
	public void setComSuc23(Integer comSuc23) {
		this.comSuc23 = comSuc23;
	}

	/**
	 * This method returns the value of the database column pack_data_info.com_suc_24  
	 * @return the value of pack_data_info.com_suc_24
	 */
	public Integer getComSuc24() {
		return comSuc24;
	}

	/**
	 * This method sets the value of the database column pack_data_info.com_suc_24  
	 * @param comSuc24 the value for pack_data_info.com_suc_24
	 */
	public void setComSuc24(Integer comSuc24) {
		this.comSuc24 = comSuc24;
	}

	/**
	 * This method returns the value of the database column pack_data_info.passive_balance  是否支持被动均衡，1支持，0支持
	 * @return the value of pack_data_info.passive_balance
	 */
	public Byte getPassiveBalance() {
		return passiveBalance;
	}

	/**
	 * This method sets the value of the database column pack_data_info.passive_balance  是否支持被动均衡，1支持，0支持
	 * @param passiveBalance the value for pack_data_info.passive_balance
	 */
	public void setPassiveBalance(Byte passiveBalance) {
		this.passiveBalance = passiveBalance;
	}

	/**
	 * This method returns the value of the database column pack_data_info.initiative_balance  是否支持主动均衡，1支持，0支持,1就是复用设备，其他诊断设备
	 * @return the value of pack_data_info.initiative_balance
	 */
	public Byte getInitiativeBalance() {
		return initiativeBalance;
	}

	/**
	 * This method sets the value of the database column pack_data_info.initiative_balance  是否支持主动均衡，1支持，0支持,1就是复用设备，其他诊断设备
	 * @param initiativeBalance the value for pack_data_info.initiative_balance
	 */
	public void setInitiativeBalance(Byte initiativeBalance) {
		this.initiativeBalance = initiativeBalance;
	}
}