package com.station.moudles.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table raw_rcv_data  
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value = "RawRcvData", description = "RawRcvData描述")
public class RawRcvData {
	/**
	 * This field corresponds to the database column raw_rcv_data.id  
	 */
	@ApiModelProperty(value = "pk", required = true)
	private Integer id;

	/**
	 * This field corresponds to the database column raw_rcv_data.gprs_id  
	 */
	@ApiModelProperty(value = "gprsId", example = "gprsId", required = false)
	private String gprsId;

	/**
	 * This field corresponds to the database column raw_rcv_data.raw_data  
	 */
	@ApiModelProperty(value = "rawData", example = "rawData", required = false)
	private String rawData;

	/**
	 * This field corresponds to the database column raw_rcv_data.rcv_time  
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@ApiModelProperty(value = "rcvTime")
	private Date rcvTime;

	/**
	 * This method returns the value of the database column raw_rcv_data.id  
	 * @return the value of raw_rcv_data.id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method sets the value of the database column raw_rcv_data.id  
	 * @param id the value for raw_rcv_data.id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method returns the value of the database column raw_rcv_data.gprs_id  
	 * @return the value of raw_rcv_data.gprs_id
	 */
	public String getGprsId() {
		return gprsId;
	}

	/**
	 * This method sets the value of the database column raw_rcv_data.gprs_id  
	 * @param gprsId the value for raw_rcv_data.gprs_id
	 */
	public void setGprsId(String gprsId) {
		this.gprsId = gprsId == null ? null : gprsId.trim();
	}

	/**
	 * This method returns the value of the database column raw_rcv_data.raw_data  
	 * @return the value of raw_rcv_data.raw_data
	 */
	public String getRawData() {
		return rawData;
	}

	/**
	 * This method sets the value of the database column raw_rcv_data.raw_data  
	 * @param rawData the value for raw_rcv_data.raw_data
	 */
	public void setRawData(String rawData) {
		this.rawData = rawData == null ? null : rawData.trim();
	}

	/**
	 * This method returns the value of the database column raw_rcv_data.rcv_time  
	 * @return the value of raw_rcv_data.rcv_time
	 */
	public Date getRcvTime() {
		return rcvTime;
	}

	/**
	 * This method sets the value of the database column raw_rcv_data.rcv_time  
	 * @param rcvTime the value for raw_rcv_data.rcv_time
	 */
	public void setRcvTime(Date rcvTime) {
		this.rcvTime = rcvTime;
	}
}