package com.station.moudles.entity;

import java.util.Date;

import org.springframework.web.jsf.FacesContextUtils;

import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by Bill Generator.
 * This class corresponds to the database table routing_inspections  巡检记录
 *
 * @zdmgenerated 2017-13-19 07:13
 */
@ApiModel(value = "巡检记录", description = "巡检记录描述")
public class RoutingInspections {
	/**
	 * This field corresponds to the database column routing_inspections.routing_inspection_id  
	 */
	@ApiModelProperty(value = "pk", required = true)
	private Integer routingInspectionId;
	/**
	 * This field corresponds to the database column routing_inspections.station_id  
	 */
	@ApiModelProperty(value = "stationId", required = false)
	private Integer stationId;
	/**
	 * This field corresponds to the database column routing_inspections.operate_type  1首次安装，2更换主从机，3更换单体
	 */
	@ApiModelProperty(value = "1首次安装，2更换主从机，3更换单体", required = false)
	private Integer operateType;
	/**
	 * This field corresponds to the database column routing_inspections.operate_id  
	 */
	@ApiModelProperty(value = "operateId", required = false)
	private Integer operateId;
	/**
	 * This field corresponds to the database column routing_inspections.operate_name  
	 */
	@ApiModelProperty(value = "operateName", example = "operateName", required = false)
	private String operateName;
	/**
	 * This field corresponds to the database column routing_inspections.operate_time  
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	@ApiModelProperty(value = "operateTime")
	private Date operateTime;
	/**
	 * This field corresponds to the database column routing_inspections.routing_inspection_status  1成功，2安装维护中
	 */
	//原来的@ApiModelProperty(value = "1成功，2安装维护中", required = false)
	@ApiModelProperty(value = "1安装维护中 ,2成功,3 失败" , required = false)
	private Integer routingInspectionStatus;
	@ApiModelProperty(value = "gprsId", example = "gprsId", required = false)
	private String gprsId;

	@ApiModelProperty(value = "confirmOperateId", required = false)
	private Integer confirmOperateId;
	
	@ApiModelProperty(value = "confirmOperateName", example = "confirmOperateName", required = false)
	private String confirmOperateName;
	//操作人员电话
	@ApiModelProperty(value = "operatePhone", example = "operatePhone", required = false)
	private String operatePhone;

	@ApiModelProperty(value = "巡检记录备注",required = false)
	private String remark;
	
	@ApiModelProperty(value = "设备类型", required = false)
	private Integer deviceType;
	

	//结束时间
	private Date endTime;

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(Integer deviceType) {
		this.deviceType = deviceType;
	}


	public String getOperatePhone() {
		return operatePhone;
	}

	public void setOperatePhone(String operatePhone) {
		this.operatePhone = operatePhone;
	}


	public String getGprsId() {
		return gprsId;
	}

	public void setGprsId(String gprsId) {
		this.gprsId = gprsId;
	}

	/**
	 * This method returns the value of the database column routing_inspections.routing_inspection_id  
	 * @return the value of routing_inspections.routing_inspection_id
	 */
	public Integer getRoutingInspectionId() {
		return routingInspectionId;
	}

	/**
	 * This method sets the value of the database column routing_inspections.routing_inspection_id  
	 * @param routingInspectionId the value for routing_inspections.routing_inspection_id
	 */
	public void setRoutingInspectionId(Integer routingInspectionId) {
		this.routingInspectionId = routingInspectionId;
	}

	/**
	 * This method returns the value of the database column routing_inspections.station_id  
	 * @return the value of routing_inspections.station_id
	 */
	public Integer getStationId() {
		return stationId;
	}

	/**
	 * This method sets the value of the database column routing_inspections.station_id  
	 * @param stationId the value for routing_inspections.station_id
	 */
	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	/**
	 * This method returns the value of the database column routing_inspections.operate_type  1首次安装，2更换主从机，3更换单体
	 * @return the value of routing_inspections.operate_type
	 */
	public Integer getOperateType() {
		return operateType;
	}

	/**
	 * This method sets the value of the database column routing_inspections.operate_type  1首次安装，2更换主从机，3更换单体
	 * @param operateType the value for routing_inspections.operate_type
	 */
	public void setOperateType(Integer operateType) {
		this.operateType = operateType;
	}

	/**
	 * This method returns the value of the database column routing_inspections.operate_id  
	 * @return the value of routing_inspections.operate_id
	 */
	public Integer getOperateId() {
		return operateId;
	}

	/**
	 * This method sets the value of the database column routing_inspections.operate_id  
	 * @param operateId the value for routing_inspections.operate_id
	 */
	public void setOperateId(Integer operateId) {
		this.operateId = operateId;
	}

	/**
	 * This method returns the value of the database column routing_inspections.operate_name  
	 * @return the value of routing_inspections.operate_name
	 */
	public String getOperateName() {
		return operateName;
	}

	/**
	 * This method sets the value of the database column routing_inspections.operate_name  
	 * @param operateName the value for routing_inspections.operate_name
	 */
	public void setOperateName(String operateName) {
		this.operateName = operateName == null ? null : operateName.trim();
	}

	/**
	 * This method returns the value of the database column routing_inspections.operate_time  
	 * @return the value of routing_inspections.operate_time
	 */
	public Date getOperateTime() {
		return operateTime;
	}

	/**
	 * This method sets the value of the database column routing_inspections.operate_time  
	 * @param operateTime the value for routing_inspections.operate_time
	 */
	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	/**
	 * This method returns the value of the database column routing_inspections.routing_inspection_status  1成功，2安装维护中
	 * @return the value of routing_inspections.routing_inspection_status
	 */
	public Integer getRoutingInspectionStatus() {
		return routingInspectionStatus;
	}

	/**
	 * This method sets the value of the database column routing_inspections.routing_inspection_status  1成功，2安装维护中
	 * @param routingInspectionStatus the value for routing_inspections.routing_inspection_status
	 */
	public void setRoutingInspectionStatus(Integer routingInspectionStatus) {
		this.routingInspectionStatus = routingInspectionStatus;
	}

	public Integer getConfirmOperateId() {
		return confirmOperateId;
	}

	public void setConfirmOperateId(Integer confirmOperateId) {
		this.confirmOperateId = confirmOperateId;
	}

	public String getConfirmOperateName() {
		return confirmOperateName;
	}

	public void setConfirmOperateName(String confirmOperateName) {
		this.confirmOperateName = confirmOperateName;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}